wasmi-labs/wasmi

src/func.rs
src/memory.rs
src/module.rs
src/runner.rs
src/table.rs
src/types.rs
src/value.rs

Couple of fixes, mainly reported by clippy

Couple of fixes

---

src/func.rs
src/global.rs
src/host.rs
src/memory.rs
src/table.rs
src/types.rs

First iteration on documentation.

---

src/host.rs
src/imports.rs

Second iteration on documenation.

---

spec/src/run.rs
src/func.rs
src/host.rs
src/imports.rs
src/lib.rs
src/memory.rs
src/module.rs
src/tests/host.rs

Third iteration on documenation.

---

.travis.yml
examples/interpret.rs
examples/invoke.rs
examples/tictactoe.rs
spec/src/run.rs
src/func.rs
src/global.rs
src/imports.rs
src/lib.rs
src/memory.rs
src/module.rs
src/table.rs
src/tests/host.rs
src/tests/wasm.rs
src/types.rs

cc #3 
This also fixes deadlinks installation from https://github.com/pepyakin/wasmi/pull/20

4th iteration on documentation

---

src/lib.rs
src/runner.rs

If you look close enough you will realize that these are actually same thing.

Merge signature mismatch traps

---

tests/spec/run.rs

If module will failed to load, one could just check line number of the original script.

Make it easier to work with spec testsuite

---

src/validation/func.rs

Fixes #63
Fix is simple: all labels refered by the br_table instruction must have same value type (or NoResult in case if they don't have result). So we just take the default label and check other labels against it.

Fix br_table validation

---

Cargo.toml
src/value.rs
tests/spec/mod.rs

And also enable:
- "conversions",
- "float_exprs",
- "float_literals",
- "float_memory",
tests.

Use f32/f64::from_bits.

---

src/validation/func.rs

Fix br_if and then tee_local validation.

---

src/lib.rs
src/validation/mod.rs

Optionally deny floating point operations

---

src/memory.rs

This allows zero-copy access to the linear memory.
Closes #27

Provide direct access to the underlying buffer

---

src/func.rs
src/isa.rs
src/module.rs

Sorry for these small fixes, these typos pop up from my IDE and I can't help fixing them :)

Typo fixes

---

src/memory.rs
src/value.rs

Remove some unsafety

---

src/lib.rs
src/value.rs

Export LittleEndianConvert

---

.travis.yml
src/memory.rs

Run rustfmt check on CI

---

src/module.rs

Add a check if NotStartedModuleRef has a start function

---

src/runner.rs

This avoids the main overhead of repeated export invocations by making it optional to clear the value stack after each interpreter run.
This is especially useful if different exports of the same module are invoked repeated so that no unintended information leaks are possible.

Make clearing value stack between export invocations optional

---

.travis.yml
Cargo.toml
benches/src/lib.rs
src/func.rs
src/host.rs
src/imports.rs
src/isa.rs
src/lib.rs
src/memory/mod.rs
src/memory/vec_bytebuf.rs
src/module.rs
src/nan_preserving_float.rs
src/prepare/compile.rs
src/prepare/mod.rs
src/runner.rs
src/table.rs
validation/src/context.rs
validation/src/func.rs
validation/src/lib.rs
validation/src/stack.rs
validation/src/util.rs

(from the nightly version)
wasmi-validation didn't have any issues.
TODO:

Apply cargo-fix on wasmi

---

Cargo.toml
src/module.rs
src/prepare/compile.rs
validation/Cargo.toml
validation/src/func.rs
validation/src/lib.rs

Update parity-wasm to 0.39.0

---

validation/src/lib.rs
validation/src/tests.rs

Allow mutable exported global. Fix #137

---

examples/invoke.rs
examples/tictactoe.rs
src/func.rs
src/host.rs
src/imports.rs
src/isa.rs
src/lib.rs
src/memory/mod.rs
src/module.rs
src/prepare/compile.rs
src/prepare/mod.rs
src/prepare/tests.rs
src/runner.rs
src/table.rs
src/tests/host.rs
src/tests/mod.rs
src/tests/wasm.rs
src/types.rs
src/value.rs
tests/spec/run.rs
validation/src/func.rs
validation/src/lib.rs
validation/src/stack.rs

Implements: https://github.com/paritytech/wasmi/issues/194
In a few cases a clippy annotation was provided to ignore the clippy warning.
- https://rust-lang.github.io/rust-clippy/master/index.html#expect_fun_call
- https://rust-lang.github.io/rust-clippy/master/index.html#manual_range_contains

Applies all clippy suggestions

---

src/func.rs
src/memory/mod.rs
src/nan_preserving_float.rs
src/prepare/compile.rs
src/types.rs
tests/spec/run.rs
validation/src/func.rs
validation/src/lib.rs

Prevent a warning while running the tests.

Minor fix to prevent a warning related to Rust 2021 in the tests

---

Cargo.toml
validation/Cargo.toml

Apart from adding the `reduced-stack-buffer` feature there were only refactoring changes not touching any API. I will do a tag and a release to crates.io after this is merged.

Bump fix version

---

.github/workflows/rust.yml

GHA: Run tests on multiple platforms

---

CHANGELOG.md

Based on "Keep a Changelog".
Also added changelog for versions 0.9.0 and 0.9.1.

Add Changelog based on "Keep a Changelog"

---

CHANGELOG.md
Cargo.toml

In preparation of the release of version `0.10.0`.

Bump version 0.9.1 -> 0.10.0

---

Cargo.toml
src/memory/mod.rs

In preparation of tackling https://github.com/paritytech/wasmi/pull/309 again.

Update small dependencies

---

.github/workflows/rust.yml
Cargo.toml
src/lib.rs
tests/spec/mod.rs
wasmi_v1/Cargo.toml

This PR allows to conditionally enable or disable the new `wasmi_v1` implementation.
Partially implements https://github.com/paritytech/wasmi/issues/306.

Add v1 crate feature for conditional wasmi_v1 usage

---

tests/e2e/v1/func.rs
wasmi_v1/src/engine/call_stack.rs
wasmi_v1/src/engine/exec_context.rs
wasmi_v1/src/engine/mod.rs
wasmi_v1/src/engine/traits.rs
wasmi_v1/src/error.rs
wasmi_v1/src/func/error.rs
wasmi_v1/src/func/into_func.rs
wasmi_v1/src/func/mod.rs
wasmi_v1/src/func/typed_func.rs
wasmi_v1/src/lib.rs

Closes https://github.com/paritytech/wasmi/issues/303.

Implement TypedFunc API

---

core/src/lib.rs
core/src/value.rs
tests/spec/v1/mod.rs
wasmi_v1/src/engine/bytecode/mod.rs
wasmi_v1/src/engine/bytecode/visitor.rs
wasmi_v1/src/engine/code_map.rs
wasmi_v1/src/engine/exec_context.rs
wasmi_v1/src/engine/func_builder/mod.rs
wasmi_v1/src/module/compile/mod.rs
wasmi_v1/src/module/compile/operator.rs

Closes https://github.com/paritytech/wasmi/issues/356.

Support `sign-extension-ops` Wasm proposal

---

CHANGELOG.md
Cargo.toml

Fixes https://github.com/paritytech/wasmi/issues/395.

Update wasmi 0.12 -> 0.13

---

core/src/nan_preserving_float.rs

This also adds a Display impl to both types and adds docs to all methods.

Improve F32 and F64 codegen

---

crates/wasmi/src/func/error.rs
crates/wasmi/src/func/mod.rs
crates/wasmi/src/func/typed_func.rs
crates/wasmi/src/func_type.rs
crates/wasmi/src/store.rs
crates/wasmi/tests/e2e/v1/func.rs

Refactor FuncType verification

---

README.md
SECURITY.md

Fix README benchmark section and add SECURITY.md

---

crates/wasmi/src/engine/executor.rs

This introduces the `try_next_instr` convenience method and adds docs to some internal executor methods.

Clean up the `wasmi` executor slightly

---

crates/core/src/untyped.rs
crates/wasmi/src/engine/config.rs
crates/wasmi/src/engine/executor.rs
crates/wasmi/src/engine/mod.rs
crates/wasmi/src/lib.rs
crates/wasmi/tests/e2e/v1/fuel_consumption_mode.rs
crates/wasmi/tests/e2e/v1/mod.rs

Closes https://github.com/paritytech/wasmi/issues/702.

Add fuel consumption modes

---

crates/cli/src/args.rs
crates/cli/src/context.rs
crates/cli/src/main.rs
crates/wasmi/benches/benches.rs
crates/wasmi/src/engine/code_map.rs
crates/wasmi/src/engine/config.rs
crates/wasmi/src/engine/mod.rs
crates/wasmi/src/engine/translator/mod.rs

Closes https://github.com/paritytech/wasmi/issues/853.

Add lazy validation compilation mode

---

crates/wasmi/src/engine/translator/mod.rs
crates/wasmi/src/error.rs

fix: typos

---

crates/wasmi/src/engine/translator/instr_encoder.rs
crates/wasmi/src/engine/translator/tests/regression/conditional_preserve.rs

Fixes https://github.com/wasmi-labs/wasmi/issues/934 together with https://github.com/wasmi-labs/wasmi/pull/945.

Avoid overwriting preservation slots before use

---

.github/workflows/publish-benchmarks.yml
.github/workflows/rust.yml
CHANGELOG.md
CONTRIBUTING.md
Cargo.toml
README.md

These links probably have been forgotten during https://github.com/wasmi-labs/wasmi/pull/930.

Update remaining old links

---

crates/collections/src/arena/component_vec.rs
crates/collections/src/arena/dedup.rs
crates/collections/src/arena/guarded.rs
crates/collections/src/arena/mod.rs
crates/collections/src/map.rs
crates/collections/src/set.rs
crates/collections/src/string_interner.rs
crates/collections/src/string_interner/detail.rs

- Add `#[inline]` to most methods
- Add `size_hint` forwarding in `Iterator` implementations

Improve `wasmi_collections` crate

---

crates/wasmi/src/engine/cache.rs
crates/wasmi/src/engine/executor/instrs.rs
crates/wasmi/src/engine/executor/instrs/call.rs
crates/wasmi/src/engine/executor/instrs/return_.rs

Benchmarks locally show slight improvements for certain test cases.

Optimize call instruction execution

---

crates/wasmi/src/engine/bytecode/construct.rs
crates/wasmi/src/engine/bytecode/mod.rs
crates/wasmi/src/engine/executor/instrs.rs
crates/wasmi/src/engine/executor/instrs/comparison.rs
crates/wasmi/src/engine/translator/instr_encoder.rs
crates/wasmi/src/engine/translator/relink_result.rs
crates/wasmi/src/engine/translator/visit_register.rs

This helps to simplify integration of https://github.com/wasmi-labs/wasmi/pull/1152.

Use named fields for Wasmi compare instructions

---

crates/wasmi/src/engine/bytecode/construct.rs
crates/wasmi/src/engine/bytecode/mod.rs
crates/wasmi/src/engine/bytecode/tests.rs
crates/wasmi/src/engine/bytecode/utils.rs
crates/wasmi/src/engine/executor/instrs.rs
crates/wasmi/src/engine/executor/instrs/binary.rs
crates/wasmi/src/engine/executor/instrs/comparison.rs
crates/wasmi/src/engine/translator/instr_encoder.rs
crates/wasmi/src/engine/translator/relink_result.rs
crates/wasmi/src/engine/translator/visit_register.rs

Use named fields for Wasmi binary instructions

---

crates/wasmi/src/engine/bytecode/construct.rs
crates/wasmi/src/engine/bytecode/mod.rs
crates/wasmi/src/engine/bytecode/tests.rs
crates/wasmi/src/engine/bytecode/utils.rs
crates/wasmi/src/engine/executor/instrs.rs
crates/wasmi/src/engine/executor/instrs/conversion.rs
crates/wasmi/src/engine/executor/instrs/unary.rs
crates/wasmi/src/engine/translator/relink_result.rs
crates/wasmi/src/engine/translator/visit_register.rs

Use named fields for Wasmi unary instructions

---

crates/wasmi/src/engine/bytecode/construct.rs
crates/wasmi/src/engine/bytecode/mod.rs
crates/wasmi/src/engine/bytecode/utils.rs
crates/wasmi/src/engine/executor/cache.rs
crates/wasmi/src/engine/executor/instrs.rs
crates/wasmi/src/engine/executor/instrs/call.rs
crates/wasmi/src/engine/executor/instrs/global.rs
crates/wasmi/src/engine/executor/instrs/memory.rs
crates/wasmi/src/engine/executor/instrs/table.rs
crates/wasmi/src/engine/translator/mod.rs
crates/wasmi/src/engine/translator/relink_result.rs
crates/wasmi/src/engine/translator/tests/fuzz/mod.rs
crates/wasmi/src/engine/translator/tests/op/br_table.rs
crates/wasmi/src/engine/translator/tests/op/call/imported.rs
crates/wasmi/src/engine/translator/tests/op/call/indirect.rs
crates/wasmi/src/engine/translator/tests/op/cmp_br.rs
crates/wasmi/src/engine/translator/tests/op/global_get.rs
crates/wasmi/src/engine/translator/tests/op/global_set.rs
crates/wasmi/src/engine/translator/tests/op/if_.rs
crates/wasmi/src/engine/translator/tests/op/local_set.rs
crates/wasmi/src/engine/translator/tests/op/return_call/imported.rs
crates/wasmi/src/engine/translator/tests/op/return_call/indirect.rs
crates/wasmi/src/engine/translator/visit.rs

Rename Wasmi bytecode index types

---

crates/wasmi/src/engine/translator/instr_encoder.rs
crates/wasmi/src/engine/translator/mod.rs
crates/wasmi/src/engine/translator/utils.rs

This PR simplifies integration of https://github.com/wasmi-labs/wasmi/pull/1152.

Add extension traits for `wasmi_ir` related types

---

crates/wasmi/src/engine/bytecode/mod.rs
crates/wasmi/src/engine/executor/instrs/memory.rs
crates/wasmi/src/engine/executor/instrs/table.rs
crates/wasmi/src/engine/translator/tests/fuzz/mod.rs
crates/wasmi/src/engine/translator/tests/op/br_table.rs
crates/wasmi/src/engine/translator/tests/op/call/imported.rs
crates/wasmi/src/engine/translator/tests/op/call/indirect.rs
crates/wasmi/src/engine/translator/tests/op/cmp_br.rs
crates/wasmi/src/engine/translator/tests/op/global_get.rs
crates/wasmi/src/engine/translator/tests/op/global_set.rs
crates/wasmi/src/engine/translator/tests/op/if_.rs
crates/wasmi/src/engine/translator/tests/op/local_set.rs
crates/wasmi/src/engine/translator/tests/op/return_call/imported.rs
crates/wasmi/src/engine/translator/tests/op/return_call/indirect.rs
crates/wasmi/src/engine/translator/visit.rs

Simplifies integration of https://github.com/wasmi-labs/wasmi/pull/1152

Create `index` submodule in `bytecode` module

---

Cargo.lock
crates/wasmi/Cargo.toml

Follow-up from https://github.com/wasmi-labs/wasmi/pull/1184.

Remove `num-derive` and `num-traits` deps where possible

---

crates/core/src/untyped.rs
crates/core/src/value.rs

Minor code move & clean-up

---

Cargo.lock
crates/fuzz/Cargo.toml
crates/fuzz/src/config.rs
fuzz/Cargo.toml

Update `wasm-tools` dependencies

---

crates/c_api/Cargo.toml
crates/c_api/src/config.rs
crates/c_api/src/engine.rs
crates/c_api/src/extern.rs
crates/c_api/src/foreign.rs
crates/c_api/src/frame.rs
crates/c_api/src/func.rs
crates/c_api/src/global.rs
crates/c_api/src/instance.rs
crates/c_api/src/lib.rs
crates/c_api/src/memory.rs
crates/c_api/src/module.rs
crates/c_api/src/ref.rs
crates/c_api/src/store.rs
crates/c_api/src/table.rs
crates/c_api/src/trap.rs
crates/c_api/src/types/export.rs
crates/c_api/src/types/extern.rs
crates/c_api/src/types/func.rs
crates/c_api/src/types/global.rs
crates/c_api/src/types/import.rs
crates/c_api/src/types/memory.rs
crates/c_api/src/types/table.rs
crates/c_api/src/types/val.rs
crates/c_api/src/val.rs
crates/c_api/src/vec.rs

feat: Add the `mangle-symbols` feature

---

NEWS.md

Remove time association of audit in news

---

crates/wasmi/src/engine/executor/instrs/call.rs
crates/wasmi/src/engine/limits/engine.rs

Hey !
I fixed several spelling issues. Glad I could help.
Br, Cal

chore: fix typos

---

.github/workflows/rust.yml

Bump from `nightly-2024-10-18` to `nightly-2025-03-01`.

Update CI `fuzz` job Rust `nightly` version

---

crates/ir/src/primitive.rs
crates/wasmi/src/engine/translator/tests/fuzz/mod.rs
crates/wasmi/src/engine/translator/tests/op/load.rs
crates/wasmi/src/engine/translator/tests/op/mod.rs
crates/wasmi/src/engine/translator/tests/op/store/mod.rs

This impl was marked as TODO for removal but was forgotten so we do it now.

Remove faulty `From<u32> for Address32` impl

---

crates/cli/src/context.rs
crates/core/src/untyped.rs
crates/fuzz/src/config.rs
crates/fuzz/src/oracle/wasmi.rs
crates/fuzz/src/oracle/wasmi_stack.rs
crates/fuzz/src/oracle/wasmtime.rs
crates/ir/src/enum.rs
crates/ir/src/for_each_op.rs
crates/ir/src/span.rs
crates/ir/src/visit_regs.rs
crates/wasmi/src/engine/config.rs
crates/wasmi/src/engine/executor/instrs.rs
crates/wasmi/src/engine/executor/instrs/wide_arithmetic.rs
crates/wasmi/src/engine/translator/mod.rs
crates/wasmi/src/engine/translator/visit.rs
crates/wasmi/tests/spec/mod.rs

Closes https://github.com/wasmi-labs/wasmi/issues/1369.

Add support for the Wasm `wide-arithmetic` proposal

---

crates/cli/src/main.rs

Closes https://github.com/wasmi-labs/wasmi/issues/1434

`wasmi_cli`: reformat multiple outputs

---

crates/core/src/simd.rs
crates/wasmi/src/engine/executor/instrs/simd.rs
crates/wasmi/src/engine/translator/simd/mod.rs

Closes https://github.com/wasmi-labs/wasmi/issues/1441

Make `IntoLaneIdx` trait public and refactor `simd` internals

---

crates/wasmi/src/engine/executor/instrs.rs
crates/wasmi/src/engine/executor/instrs/call.rs
crates/wasmi/src/store.rs

Carved out from https://github.com/wasmi-labs/wasmi/pull/1449

Add `Store<T>::inner[_mut]` getters

---

crates/wasmi/src/engine/executor/instrs/call.rs
crates/wasmi/src/engine/translator/mod.rs
crates/wasmi/src/store.rs

Carved out improvements from https://github.com/wasmi-labs/wasmi/pull/1449

Wasmi executor and store improvements

---

crates/core/src/typed.rs
crates/core/src/value.rs
crates/core/src/wasm.rs
crates/wasmi/src/engine/translator/mod.rs
crates/wasmi/src/engine/translator/visit.rs

Closes https://github.com/wasmi-labs/wasmi/issues/1440

Remove `TypedVal` API

---

crates/wasmi/src/engine/executor/mod.rs
crates/wasmi/src/engine/mod.rs
crates/wasmi/src/module/mod.rs
crates/wasmi/tests/integration/fuel_consumption.rs
crates/wasmi/tests/integration/fuel_metering.rs

The new pr for https://github.com/wasmi-labs/wasmi/pull/1455

chore: fix some comments

---

crates/core/src/fuel.rs
crates/wasmi/src/engine/code_map.rs
crates/wasmi/src/engine/config.rs
crates/wasmi/src/engine/executor/instrs/memory.rs
crates/wasmi/src/engine/mod.rs
crates/wasmi/src/engine/translator/instr_encoder.rs
crates/wasmi/src/engine/translator/mod.rs
crates/wasmi/src/engine/translator/simd/mod.rs
crates/wasmi/src/engine/translator/simd/visit.rs
crates/wasmi/src/engine/translator/visit.rs
crates/wasmi/src/memory/mod.rs
crates/wasmi/src/store.rs
crates/wasmi/src/table/mod.rs

Carved out from https://github.com/wasmi-labs/wasmi/pull/1460.

Rename `FuelCosts` API and made anticipatory adjustments

---

crates/wasmi/src/engine/config.rs
crates/wasmi/src/engine/mod.rs
crates/wasmi/src/engine/translator/instr_encoder.rs
crates/wasmi/src/engine/translator/mod.rs
crates/wasmi/src/engine/translator/visit.rs
crates/wasmi/src/store.rs
crates/wast/src/lib.rs

Carved out from https://github.com/wasmi-labs/wasmi/pull/1460.
This is in anticipation to simplify merging the original PR.

Make `Config` and `FuelCostsProvider` non-`Copy`

---

crates/wasmi/src/table/element.rs

Carved out from #1460.
This is in anticipation to simplify merging the original PR.

Make `ElementSegmentEntity` constructor simpler

---

crates/wasmi/src/global.rs
crates/wasmi/src/instance/tests.rs
crates/wasmi/src/memory/error.rs
crates/wasmi/src/module/instantiate/error.rs
crates/wasmi/src/module/instantiate/mod.rs
crates/wasmi/src/module/instantiate/pre.rs
crates/wasmi/src/store.rs
crates/wasmi/src/table/error.rs
crates/wasmi/src/table/mod.rs

Redesign `InstantationError`

---

crates/wasmi/src/engine/mod.rs
crates/wasmi/src/linker.rs
crates/wasmi/src/module/init_expr.rs
crates/wast/src/lib.rs

chore: fix some typos in comment

---

crates/ir/src/for_each_op.rs
crates/wasmi/src/engine/executor/instrs.rs
crates/wasmi/src/engine/executor/instrs/binary.rs
crates/wasmi/src/engine/executor/instrs/table.rs
crates/wasmi/src/engine/translator/tests/op/table/table_copy.rs
crates/wasmi/src/engine/translator/visit.rs

Not a Wasmi bug or issue but this fixes an annoying issue I am seeing with `rust-analyzer` lately.

Fix `rust-analyzer` issues

---

crates/wasmi/src/engine/executor/instrs/memory.rs
crates/wasmi/src/engine/executor/instrs/table.rs
crates/wasmi/src/store/mod.rs
crates/wasmi/src/store/pruned.rs
crates/wasmi/src/store/typeid.rs

Closes https://github.com/wasmi-labs/wasmi/issues/1503.
cc @juntyr

Drop `T: 'static` bounds from `wasmi::Store` again

---

crates/wasmi/src/engine/translator/func/instr_encoder.rs
crates/wasmi/src/engine/translator/mod.rs
crates/wasmi/src/engine/translator/utils.rs

The new `IsInstructionParameter` ext-trait is useful for debugging.

Move `BumpFuelConsumption` ext-trait and add `IsInstructionParameter` ext-trait

---

crates/wasi/src/sync/mod.rs
crates/wasi/src/sync/snapshots/preview_1.rs
crates/wasmi/src/lib.rs
crates/wasmi/src/linker.rs

Closes https://github.com/wasmi-labs/wasmi/issues/1573.

Deprecate `LinkerBuilder` type

---

crates/ir/src/for_each_op.rs
crates/wasmi/src/engine/executor/instrs.rs
crates/wasmi/src/engine/executor/instrs/branch.rs
crates/wasmi/src/engine/executor/instrs/return_.rs
crates/wasmi/src/engine/translator/comparator.rs
crates/wasmi/src/engine/translator/func/mod.rs
crates/wasmi/src/engine/translator/utils.rs

Closes https://github.com/wasmi-labs/wasmi/issues/1608.

Remove unused `br_table` Wasmi instruction variants

---

crates/wasmi/src/engine/code_map.rs
crates/wasmi/tests/integration/fuel_metering.rs

Closes https://github.com/wasmi-labs/wasmi/issues/1647.

Fix lazy translation when running into `out of fuel`
