wasmi-labs/wasmi

src/host.rs, src/tests/mod.rs
As per [C-GOOD-ERR](https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#c-good-err)
=> Make Error: Sync + Send

examples/tictactoe.rs, spec/src/run.rs, src/common/stack.rs, src/func.rs, src/host.rs, src/lib.rs, src/module.rs, src/runner.rs, src/table.rs, src/tests/host.rs, src/value.rs
Wasm function can fail only by trapping (e.g. invoking wasm function can't result in linkage error). This means we can benefit from introducing special error type for traps.
=> Wasm function can only trap

src/common/mod.rs, src/runner.rs, src/validation/func.rs
These limits seems to be picked arbitrary, and I just made it arbitrary larger.
Anyway, we need to reconsider these limits, ideally providing to the user a way to customize the limits. (#51)
FWIW, When the last time I've tried to run gcc's torture testsuite with wasmi it also bumped into this limit.
Fixes #41.
=> Just bump framestack limits.

src/runner.rs, src/value.rs
`RuntimeValue::default` takes `parity_wasm::elements::ValueType` as an input parameter. This change fixes it to be wasmi's `ValueType`.
=> Use wasmi ValueType for RuntimeValue instead pwasm

src/bin/instantiate.rs, src/runner.rs, src/value.rs
This change depends on #52.
This change adds a handy utility to test whether the given module deserializes, validates and instantiates successfully.
=> Add `instantiate` bin

src/module.rs, tests/spec/run.rs
The bug was about instantiating a module with elements segment being out-of-bounds, however, it was with zero length. E.g.:
```
(module
(table 0 anyfunc)
(elem (i32.const 1))
)
```
In our impl there was no out-of-bounds, because there was no attempt to set any table entry.
This change adds early check for specifically this case.
=> Update spec testsuite; Fix instantiation bug

src/host.rs, src/lib.rs, src/runner.rs, src/value.rs
When working on a integration of sandbox into a polkadot, I've encountered a situation when I needed to use `RuntimeArgs::nth` in a generic context but was unable to do so since it is impossible to call `nth` with type `T` without a `TryInto` constraint and it is also impossible to specify such constraint since `TryInto` is not exported.
Furthermore, even though `TryInto` is just a utility and user can always define conversion operations by himself, it is infeasible to extract `[RuntimeValue]` from the `RuntimeArgs` since it's not public.
=> Args refactor

Cargo.toml
1. Version bump to 0.1.0,
2. Add fields like repository and documentation,
3. Migrated to `ignore` like excludes (see https://github.com/rust-lang/cargo/issues/4268)
=> Prepare for 0.1.0

src/validation/mod.rs
=> Require func_type (not func) for func import.

src/lib.rs
So that it matches the Cargo.toml
=> Fix the name of the 32bits feature

src/runner.rs
This can guard from a rogue `Externals` implementation.
=> Check the returned value against the signature.

src/tests/mod.rs, src/value.rs
Casts have arithmetic semantics, and under some build configurations Rust will panic when encountering an arithmetic overflow. Use a transmute instead since it's what we mean. The previous code worked, but still I added a test for good measure.
=> Use transmute instead of casts in RuntimeValue conversion.

src/value.rs
This works under the assumption that these values are represented as an `I32` in WASM, which seems reasonable.
=> implement from and into RuntimeValue for i8, u8, i16 and u16

src/lib.rs
Export nan_preserving_float crate.
It might come in handy since `RuntimeValue` directly references `nan_preserving_float::{F32, F64}` types. Otherwise, user code will have to depend on the nan_preserving_float crate explicitly.
=> Export nan_preserving_float.

src/func.rs, src/lib.rs, src/runner.rs, src/tests/host.rs
Implements #85. If a trap of kind Host happens, we allow the caller to feed back in another return value for that host function, and then continue the execution.
* For interpreter, the call stack is moved to `Interpreter` struct itself. We drop the interpreter altogether for normal executions anyway. `resume_execution`, which takes the feeded-back return value, will continue the execution with the loop.
* For public interface, `invoke_resumable` is added to `FuncInstance`. This function returns a handle `FuncInvocation`. The caller can then use this to start or resume an execution.
=> Resumable function invocation

src/memory.rs, src/runner.rs, src/value.rs
=> Avoid allocations on memory operations

src/isa.rs
Removing this TODO doesn't incur any warning. So safe to remove it.
=> we don't need this TODO anymore

src/memory.rs
Add a `transfer` function to `MemoryInstance`, which allows copying memory between two, possibly distinct, memory instances.
=> Transfer function

src/isa.rs, src/runner.rs, src/validation/func.rs, src/validation/tests.rs
This PR lays some groundwork for #100.
`isa::Instructions` is now an opaque container. `current_pc(&self) -> u32` indicates the position at which the next instruction would be added, and `push(&mut self, Instruction)` actually does the adding. Currently this happens by pushing into a `Vec<Instruction>`, but this could instead encode the `Instruction` into bytecode.
`isa::Instructions` supports reading back instructions via `iterate_from(&self, pc: u32) -> InstructionIter<'>`. Again, right now that just walks the internal `Vec<Instruction>`, but it could instead sequentially decode `Instruction`s from bytecode.
Since instruction encoding is now internal to `isa::Instructions`, it also gains `patch_relocation(&mut self, Reloc, dst_pc: u32)`, and that enumeration moves to `isa::Reloc`. …
=> Hide instruction storage details

src/runner.rs
We don't have to update frame's PC on every instruction, since the iterator already keeps track of the current PC. We still need update frame's PC before leaving the current frame.
Here is benchmark results:
```
bench_regex_redux  6,678,107                       5,954,159               -723,948  -10.84%   x 1.12
bench_rev_comp     8,367,998                       7,778,885               -589,113   -7.04%   x 1.08
bench_tiny_keccak  4,247,514                       4,091,930               -155,584   -3.66%   x 1.04
fac_opt            54,793                          52,716                    -2,077   -3.79%   x 1.04
fac_recursive      57,335                          55,447                    -1,888   -3.29%   x 1.03
recursive_ok       1,352,769                       1,270,486 …
```
=> Don't update PC on every instruction

.travis.yml, Cargo.toml, benches/Cargo.toml, fuzz/Cargo.toml, hfuzz/Cargo.toml
- use gcc-8
- update wabt to 0.6.
- don't run cargo-deadlinks in CI. It keeps getting us problems, e.g. [this](https://travis-ci.org/paritytech/wasmi/jobs/444458704#L1311-L1313). It's time to get rid of it.
=> Travis maintenance

.travis.yml, Cargo.toml, README.md, src/common/stack.rs, src/func.rs, src/global.rs, src/host.rs, src/imports.rs, src/isa.rs, src/lib.rs, src/memory.rs, src/module.rs, src/nan_preserving_float.rs, src/runner.rs, src/table.rs, src/tests/host.rs, src/tests/mod.rs, src/types.rs, src/validation/context.rs, src/validation/func.rs, src/validation/mod.rs, src/validation/util.rs, src/value.rs
This PR should contain no breaking changes.
* Add a `std` feature, enabled by default and sync it with `parity-wasm/std`
* Remove uses of `std::io`
* Change to a HashMap implementation that works on `alloc`
* Disable `std::error` for `no_std`
* The biggest change is using `core` and `alloc` everywhere and substituting `std` if available.
This is -- as far as I know -- the accepted way to support `no_std` (as mentioned in the [`alloc` RFC](https://github.com/SimonSapin/rfcs/blob/liballoc/text/0000-liballoc.md)).
`no_std` should probably be added to the Travis configuration.
Nom has a working `no_std` Travis: https://github.com/Geal/nom/blob/master/.travis.yml.
=> Add no_std support

src/func.rs, src/module.rs, src/runner.rs
In `FuncInstance::invoke`, `check_function_args` is immediately called again.
=> Remove redundent check_function_args

src/runner.rs, src/value.rs
This closes #99. Benchcmp results:
```
name               preopt.bench ns/iter  postopt.bench ns/iter  diff ns/iter   diff %  speedup 
bench_regex_redux  4,471,532             4,117,821                  -353,711   -7.91%   x 1.09 
bench_rev_comp     10,363,517            9,552,537                  -810,980   -7.83%   x 1.08 
bench_tiny_keccak  5,475,809             5,044,934                  -430,875   -7.87%   x 1.09 
fac_opt            42,472                26,942                      -15,530  -36.57%   x 1.58 
fac_recursive      43,852                28,770                      -15,082  -34.39%   x 1.52 
recursive_ok       1,423,602             1,363,951                   -59,651   -4.19%   x 1.04 
recursive_trap     182,536               160,872                     -21,664  -11.87% …
```
=> Remove tag from RuntimeValue

src/isa.rs, src/runner.rs, src/validation/func.rs, src/validation/tests.rs
Closes https://github.com/paritytech/wasmi/issues/139. This also allows `Instruction` to be `Copy`, which massively speeds
up `<Instructions as Clone>::clone` since it can now just `memcpy`
the bytes using SIMD instead of having to switch on every single
element. I haven't looked at the disassembly of `InstructionIter::next`
yet, it could be that there are even more improvements yet to be gained
from either:
* Only doing work on `BrTable` (this might already be the case depending
on the whims of the optimiser),
* Using `unsafe` to make it a noop (we really don't want to do this,
obviously, since it means that `Instructions` has to be immovable).
This also paves the way for an implementation of #100 (in theory we shouldn't have to do any API breakage to implement that feature), although …
=> Remove `Box<[Target]>` from `Instruction`

src/host.rs
The example is missing two things:
* `index` is computed but not used,
* `check_signature` is never used.
This patch tries to fix that.
=> doc(host) Fix the `Externals` example

src/func.rs, src/lib.rs, src/tests/host.rs
=> Check type when resuming function

src/memory.rs
This allows reusing module instances in substrate. Memory used by each call can be tracked and cleared between calls.
=> Track memory usage

Cargo.toml, src/imports.rs, src/lib.rs, src/module.rs, src/validation/mod.rs
Hey,
So it turns out that `hashmap_core` is deprecated, I replaced it with `hashbrown` according to the maintainers suggestion here: https://github.com/Amanieu/hashmap_core/pull/10
The tests didn't pass for me locally, But I hope this is a configuration thing because I see no reason for any meaningful difference here
=> Replaced hashmap_core with hashbrown

Cargo.toml, src/lib.rs, src/value.rs
Almost all the operations Byteorder supported using IO are now possible natively.
so to not break the API the trait still accepts a mutable buffer but it transmutes the data using the native functions that were stabilized: https://github.com/rust-lang/rust/pull/53697
=> Removed Byteorder now that rust supports it natively

Cargo.toml
So, when I replaced `hashmap_core` with `hashbrown` I didn't add the nightly feature to it.
This means that it uses `std`.
source: https://github.com/Amanieu/hashbrown/blob/master/src/lib.rs#L46
=> Added the nightly feature to hashbrown

.travis.yml, src/memory.rs
The CI actually catched this: https://travis-ci.org/paritytech/wasmi/jobs/532821121#L754
So I changed the travis config to not allow nightly fails
=> Replaced std with core in the TryInto import

src/func.rs, src/lib.rs, src/module.rs, src/runner.rs
We hope to use `wasmi` to implement a policy engine for low-volume packet inspection in an embedded setting. Initial CPU profiles using toy policies showed almost 40% CPU time spent in `Vec::extend_with` to allocate and initialize a new value stack for each function call.
This MR tries to address this by adding API to allow applications to reuse stack allocations (for both value and call stacks).
As a side effect, it also provides API for applications to configure the stack size limits (which is rather useful for us as we only need a few kB of value stack in our particular application).
A micro benchmark executing a minimal policy for single packet optimized for size showed the following changes:
* Originally, an iteration took 205 µs.
* With this MR, but _without_ doing any recycling, an …
=> RFC: Recycle value stacks to avoid allocation costs

Cargo.toml, src/imports.rs, src/lib.rs, src/module.rs, validation/Cargo.toml, validation/src/lib.rs
wasmi-validation must handle untrusted input and hence we switch from
Hash{Set,Map} (whether std's or hashbrown's) to BTree{Set,Map} to avoid
algorithmic complexity attacks while retaining no_std support.
Closes #183
=> Remove hashbrown and use BTree{Map,Set} from the alloc crate

.cargo/config, .travis.yml, Cargo.toml, src/lib.rs, src/value.rs, test.sh
This adds ARMv7 as test target for Travis CI so that issues on this 32-bit platform can be spotted immediately which should also resolve #43.
To do so, I opted to bump the CI to Xenial to avoid needing third-party repositories as everything just works using `crossbuild-essential-armhf` and `qemu-user-static` on this platform.
I also to install packages using `sudo apt-get` instead of the APT `addon` as the latter does not support conditional installs based on the build matrix, but I did not want to use a different installation method of the conditional and the unconditional dependencies.
**Note that the spec tests currently fail due to failures in `wasm_conversions`. I would be glad if someone could help me with fixing those.**
=> Add ARMv7 as CI test target

src/func.rs, src/tests/host.rs
Right now, if you call `invoke_resumable`, the function arguments are borrowed by the `FuncInstance`. This is very impractical, as you can't really store the `FuncInstance` in a struct for later.
This PR replaces the `&'args [RuntimeValue]` with a `Cow<'a, [RuntimeValue]>`.
This is technically a breaking change, because unfortunately the type `[RuntimeValue; N]` doesn't implement `Into<Cow<[RuntimeValue]>>`.
For example if someone was calling `invoke_resumable(&[a, b])`, it will stop compiling and they need to do `invoke_resumable(&[a, b][..])` instead.
(fwiw, this PR is for a personal project, not a paritytech thing)
=> Use a Cow for the resumable parameters

Cargo.toml, benches/Cargo.toml, fuzz/Cargo.toml, hfuzz/Cargo.toml, tests/spec/run.rs
This fixes compilation that users can get with newer GCC versions.
=> Bump wabt up to 0.9.

benches/wasm-kernel/src/lib.rs
Nightly builds reported:
```
error[E0596]: cannot borrow `*test_data.result` as mutable, as it is behind a `*const` pointer
--> src/lib.rs:40:19
|
36 | pub extern "C" fn bench_tiny_keccak(test_data: *const TinyKeccakTestData) {
|                                                ------------------------- help: consider changing this to be a mutable pointer: `*mut TinyKeccakTestData`
...
40 |         keccak.finalize((*test_data).result);
|                         ^^^^^^^^^^^^^^^^^^^ `test_data` is a `*const` pointer, so the data it refers to cannot be borrowed as mutable
```
=> Fix tiny_keccak

src/runner.rs
When heap profiling an application of ours, we noticed `FunctionContext::initialize` being responsible for most allocations¹ by count and size. As the `locals` vector is consumed immediately, it seems reasonable to not allocate it at all and push the default values onto the value stack directly. A follow-up commit then removes the repeated bounds checking by extending the value stack in a single operation as suggested by the TODO comment.
¹ Meaning two orders of magnitude more than the second hottest allocation site so that this change removes 1% CPU usage on an ARM Cortex A9 target.
=> Avoid temporary allocations during function context initialization

Cargo.toml, README.md, validation/Cargo.toml
Changes:
- Bump parity-wasm version to "0.41"; parity-wasm "0.41" no longer requires
nightly for no_std
- Edit clause in readme to show nightly is no longer needed.
=> Obviate need for a nightly compiler when building for no_std.

Cargo.toml, validation/Cargo.toml
Bump versions for wasmi and wasmi-validation in preparation for cargo publish.
Publishing a new cargo version will allow downstream crates to build in no_std
mode on rust stable (a recent change).
If someone with write access to https://crates.io/crates/wasmi could run cargo publish to update `wasmi` and `wasmi-validation` it would be appreciated. (you'll need to `cargo publish` `wasmi-validation` first because `wasmi` depends on it)
=> Bump versions for wasmi and wasmi-validation

.travis.yml, Cargo.toml, src/nan_preserving_float.rs, src/value.rs
Two issues are fixed:
1. `num-bigint 0.2` requires `std`, and is used to perform float to int conversions since #186. This patch disables this change in no_std environments. This change can be reverted once `num-bigint 0.3` is released, which will support no_std.
2. The `f{32,64}::fract` method is currently not implemented by `core`. This patch uses the no_std supporting implementation from `num-trait`'s `FloatCore` trait.
Travis tests were also updated to check the crate with `cargo no-std-check` which should fail the build if new std dependencies are added in the future.
=> Fix wasmi no_std support

Cargo.toml
Currently when compiling wasmi to targets that do not support libc, building fails even when using the `core` feature instead of the `std` feature. This PR fixes that :smiley:
=> made libc optional so that it isnt pulled when not using libstd

src/lib.rs
This sort of conversion is useful for extracting custom error types from the runtime when the error type is not Clone. Even when it is, it's more efficient to unwrap it that to clone it.
=> Added conversion from wasmi::Error to Option<Box<dyn HostError>>

src/lib.rs
PR #234 was just merged, and i realized that i'd also need access to the original error if it was not a host error.
I'm adding a `try_into_host_error` method for the `Error` type which will either unwrap the host error, or return the original error unmodified.
I'll use this space to also thank you for merging my previous PR :)
=> added Error::try_into_host_error

Cargo.toml, src/host.rs, src/lib.rs
@pepyakin Sorry for so many small PRs one after the other, this time I made sure the code does what i need it to, and added a documentation test.
The last missing piece was adding by-value downcasting functionality (as opposed to the by-reference downcast). I use the [`downcast-rs`](https://crates.io/crates/downcast-rs) crate here which provides a handy shortcut to implementing this but there's no magic happening there, as you can see in its docs. It also supports no_std as you can see.
Now I can write code like this:
```rust
let wasmi_error = /* Something that returns an instance of wasmi::Error */;
match wasmi_error.try_into_host_error() {
// host_error: Box<dyn HostError>
Ok(host_error) => match host_error.downcast::<MyError>() {
Ok(my_error) => /* my_error is a Box<MyError>. I can get …
```
=> added downcast functionality to Box<dyn HostError>

.travis.yml, Cargo.toml, README.md, examples/invoke.rs, src/memory/mod.rs, src/memory/vec_bytebuf.rs, src/prepare/tests.rs, src/tests/host.rs, src/tests/mod.rs, src/tests/wasm.rs, src/value.rs, test.sh
Just looking for something to hack on I found https://github.com/paritytech/wasmi/issues/240 and decided to give it a try.
Along they way I needed to address a few other things, so they are all included here:
- Make the `--no-default-features --features=core` configuration testable. This mostly involves manually importing std into test modules.
- One ugly part here is that I had to add some cfgs to the example program so that it works with or without the 'std' config.
- Add the core testing configuration to CI.
- Change the way vec_bytebuf was constructing itself so that it passes the test suite fast
- Restructure how the functions in libm are called since that library no longer includes the traits that were being used.
I can't verify that the libm panicking bug is actually fixed since it …
=> Upgrade libm and make no-std config testable

src/module.rs
This is to allow building and running wasmi on constrained target such as microcontroller.
This requires the ability to build without std.
=> Render constrained system friendly

src/memory/mod.rs
These are more flexible alternatives compared to `with_direct_access` and `with_direct_access_mut` which require passing closures.
=> Add MemoryInstance::direct_access and direct_access_mut

Cargo.toml, validation/Cargo.toml
The major bump is necessary because it exposes parity-wasm in it's public interface and that got a major bump.
CI is already failing in master. Unrelated to this PR.
=> Bump validation version

Cargo.toml
This PR introduces a new feature as a forward of underlying feature introduced in https://github.com/paritytech/parity-wasm/pull/283.
=> Forward parity-wasm's feature 'reduced-stack-buffer'

README.md
Same changes as https://github.com/paritytech/wasmi/pull/258, just on current master to give CI a chance.
=> Fix Cargo.toml no_std example in readme

.github/workflows/rust.yml, .travis.yml, Cargo.toml, src/lib.rs, src/memory/mmap_bytebuf.rs, src/memory/mod.rs, src/module.rs, src/prepare/mod.rs, validation/Cargo.toml
Closes https://github.com/paritytech/wasmi/issues/270.
In summary this PR does the following:
- Removes the `core` crate feature. Explanation can be found in #270 .
- Replaces the `vec_memory` crate feature with the new `virtual_memory` crate feature.
- The reason is that the new `virtual_memory` crate feature is additive unlike the old `vec_memory`.
- Users of the crate are recommended to enable the `virtual_memory` crate feature if they are building `wasmi` for a platform that supports OS based virtual memory. Otherwise `wasmi` will fallback onto the vector based implementation.
=> Remove core crate feature

src/imports.rs, src/nan_preserving_float.rs
New lint in `clippy` 0.1.59 caused these new warnings to pop up.
=> Apply some clippy suggestions for new #[must_use] lint

.github/workflows/rust.yml, .rustfmt.toml, benches/build.rs, examples/interpret.rs, examples/tictactoe.rs, src/bin/instantiate.rs, src/func.rs, src/global.rs, src/host.rs, src/imports.rs, src/lib.rs, src/memory/mod.rs, src/module.rs, src/nan_preserving_float.rs, src/prepare/compile.rs, src/prepare/mod.rs, src/runner.rs, src/table.rs, src/tests/host.rs, src/tests/wasm.rs, src/types.rs, src/value.rs, tests/spec/run.rs, validation/src/context.rs, validation/src/func.rs, validation/src/lib.rs, validation/src/tests.rs
Introduces the following `rustfmt` formatting configurations:
- `imports_granularity = "Crate"`:
- https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#crate
- `imports_layout = "HorizontalVertical"`:
- https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#horizontalvertical
I have applied both formatting transformations in separate commits if you want to inspect their respective outcomes.
IMO it should not be a big deal to use `nightly` `rustfmt` toolchain instead of `stable` in our GitHub Actions CI.
I am aware that it is kinda biased to not apply standard `stable` Rust formatting and that introducing unstable formatting specifiers might be unpopular, however, both formatting specifiers have been "stable" for quite some time and are probably going to be …
=> Improve imports formatting

src/memory/mod.rs, src/value.rs
This version is more efficient, smaller and more elegant than the old version.
Unfortunately this is a breaking change for implementers of the old `LittleEndianConvert` trait, however, since `wasmi` provided implementations for all necessary types this breakage will possibly be alright.
The new trait definition was a result of the work from #287.
Merging this PR will make the common base of both `v0` and `v1` implementations of `wasmi` slightly bigger.
There was no noticeable difference between the two versions, however, I think that's partially due to the fact that our benchmarks do not really test out the memory accesses in depth.
```
test bench_regex_redux ... bench:   1,807,313 ns/iter (+/- 73,280)
test bench_rev_comp    ... bench:   1,637,458 ns/iter (+/- 60,874)
test …
```
=> Introduce new more efficient LittleEndianConvert trait

src/value.rs
I discovered today that the official WebAssembly spec test suite assertions and `wasmi` results diverge in a particular case with the `copysign` instruction.
For `F32::from_bits(0xFFFC_0000).copysign(F32::from_bits(0))` the expected result according to the WebAssembly Spec test suite is `0x7FFC_0000`, however, `wasmi` currently returns `0xFFFC_0000`.
The Rust documentation mandates the same behavior from `copysign` as WebAssembly does: https://doc.rust-lang.org/std/primitive.f32.html#method.copysign
The bug was not caught because the current `wasmi` Wasm spec test runner seems to improperly handle `NaN` values.
Fortunately the bug fix was easy, however, I still wonder why we are going to great lengths like this.
=> Fix Float::copysign impl

src/value.rs
Encountered this while writing Wasm spec test suite for `v1` engine.
As in https://github.com/paritytech/wasmi/pull/293 the Wasm spec test suite for `v0` seem to not properly handle catch these cases and therefore they remained unnoticed.
Also add regression unit tests for both operations.
Now both operations adhere to the Wasm specification.
=> Fix Float::{min,max} implementations

src/runner.rs
As suggested in a review. Forgot to apply ...
=> Rename ValueStack::pop_as_slice -> pop_slice

src/lib.rs, src/value.rs
While improving the `v1` Wasm spec test suite and making it now assert expected Wasm trap message I found some inconsitencies between `wasmi` traps and the traps expected by the Wasm specification. This PR fixes it for `v0`.
=> Make wasmi traps more conformant to Wasm specification

src/v1/engine/code_map.rs, src/v1/engine/exec_context.rs
```
test bench_compile_and_validate    ... bench:   7,390,310 ns/iter (+/- 745,235)
test bench_compile_and_validate_v1 ... bench:   8,379,948 ns/iter (+/- 548,240)
test bench_instantiate_module      ... bench:     449,365 ns/iter (+/- 67,005)
test bench_instantiate_module_v1   ... bench:      63,631 ns/iter (+/- 3,750)
test bench_tiny_keccak             ... bench:   1,330,325 ns/iter (+/- 135,642)
test bench_tiny_keccak_v1          ... bench:   1,272,542 ns/iter (+/- 54,177)
test count_until                   ... bench:   1,960,267 ns/iter (+/- 162,996)
test count_until_v1                ... bench:   1,816,740 ns/iter (+/- 94,504)
test fac_opt                       ... bench:      25,026 ns/iter (+/- 1,451)
test fac_opt_v1                    ... bench:         803 ns/iter (+/- 61)
test …
```
=> Add perf sensitive inline attributes in interpreter hot path

.github/workflows/rust.yml
When working on `wasmi_core` sub crate I found that our current CI did not check certain properties of `wasmi_core`.
=> Improve CI jobs mostly by adding '--workspace' where required

src/v1/engine/code_map.rs
Are we okay with allowing optimizations using `unsafe` Rust code in the interpreter's hot path if they are safe by design?
```
test bench_compile_and_validate    ... bench:   6,963,714 ns/iter (+/- 306,278)
test bench_compile_and_validate_v1 ... bench:   8,256,357 ns/iter (+/- 1,286,043)
test bench_instantiate_module      ... bench:     423,622 ns/iter (+/- 43,379)
test bench_instantiate_module_v1   ... bench:      61,506 ns/iter (+/- 5,551)
test bench_tiny_keccak             ... bench:   1,306,960 ns/iter (+/- 101,209)
test bench_tiny_keccak_v1          ... bench:   1,260,753 ns/iter (+/- 57,078)
test count_until                   ... bench:   1,912,327 ns/iter (+/- 122,611)
test count_until_v1                ... bench:   1,798,430 ns/iter (+/- 96,263)
test fac_opt …
```
=> Eliminate bounds check in interpreter hot path

benches/src/lib.rs, examples/interpret.rs, examples/invoke.rs, examples/tictactoe.rs, src/bin/instantiate.rs, src/func.rs, src/global.rs, src/host.rs, src/lib.rs, src/module.rs, src/runner.rs, src/tests/host.rs, src/tests/mod.rs, src/tests/wasm.rs, src/types.rs, src/v1/engine/inst_builder.rs, src/v1/engine/mod.rs, src/v1/engine/value_stack.rs, src/v1/func/into_func.rs, src/v1/func/mod.rs, src/v1/global.rs, src/v1/module/compile/mod.rs, src/v1/module/instantiate.rs, src/value.rs, tests/spec/v0/run.rs, tests/spec/v1/context.rs, tests/spec/v1/run.rs
The `RuntimeValue` type is one of the most commonly used types and therefore should have a short name, however, it has one of the longest type names throughout the `wasmi` codebase.
Other Wasm engines such as Wasmtime go even further and just call it `Val`.
Since the next update is going to be a breaking one (due to the introduction of `v1`) I thought it is okay to ship with some other breaking changes. We could technically provide a type alias
```rust
#[deprecated(note = "just use Value")]
pub type RuntimeValue = Value;
```
To signal users what to do in case they don't read the changelog.
To reviewers: Review commit by commit since I separated formatting from renaming.
=> Rename RuntimeValue to Value internally

.cargo/config
Was required for our old CI but since the old CI no longer exists this also is no longer needed.
=> Remove .cargo/config folder

benches/benches.rs, tests/e2e/mod.rs, tests/e2e/v1/func.rs, tests/e2e/v1/mod.rs, wasmi_v1/src/engine/func_args.rs, wasmi_v1/src/engine/mod.rs, wasmi_v1/src/engine/value_stack.rs, wasmi_v1/src/foreach_tuple.rs, wasmi_v1/src/func/into_func.rs, wasmi_v1/src/func/mod.rs, wasmi_v1/src/lib.rs
This PR optimizes marshalling of function parameters and return values when calling host functions from Wasm execution.
This basically tries to go the optimal path where the host function parameters are read out directly from the value stack and the host function directly writes results back into the value stack.
The benchmarks show improvements between 10-15%:
- Host calls when executed from the host side now use the `v1` interpreter engine, too.
- The optimized marshalling mainly got improved for the common case where Wasm calls into the host.
- This PR implementation allows for an efficient `TypedFunc` implementation. (https://github.com/paritytech/wasmi/issues/303)
- There no longer is the need for the artificial `scratch` buffer for the `v1` engine type so this PR removes it again. …
=> Optimize marshalling

Cargo.toml, wasmi_v1/src/engine/call_stack.rs, wasmi_v1/src/engine/mod.rs, wasmi_v1/src/engine/value_stack.rs, wasmi_v1/src/module/compile/mod.rs, wasmi_v1/src/module/instantiate.rs, wasmi_v1/src/module/mod.rs
- Removes superflous `clone`
- Removes plenty of dead code
- Cleans up some engine specific code
- Removes useless assert
=> Clean up wasmi_v1 codebase

wasmi_v1/src/engine/call_stack.rs, wasmi_v1/src/engine/exec_context.rs, wasmi_v1/src/engine/mod.rs
While trying to figure out https://github.com/paritytech/wasmi/issues/339 I discovered some optimization potential for recursive calls and host calls which led to a fantastic speed up.
This basically reuses the local variable `function_frame` inside a hot loop instead of hot swapping the most recent function frame using the call stack. This behavior was inherited by the old `wasmi` engine (so we could implement an improvement there as well potentially).
```
execute/tiny_keccak/v1         time: [982.21 us 985.14 us 988.71 us]
execute/rev_complement/v1      time: [1.2141 ms 1.2168 ms 1.2200 ms]
execute/regex_redux/v1         time: [1.3259 ms 1.3288 ms 1.3322 ms]
execute/count_until/v1         time: [1.7190 ms 1.7231 ms 1.7274 ms]
execute/factorial_recursive/v1 time: [1.4232 us 1.4269 us …
```
=> Optimize recursive calls

.github/workflows/rust.yml, Cargo.toml, benches/benches.rs, examples/interpret.rs, examples/invoke.rs, examples/tictactoe.rs, src/bin/instantiate.rs, src/func.rs, src/global.rs, src/host.rs, src/lib.rs, src/module.rs, src/runner.rs, tests/e2e/mod.rs, tests/e2e/v0/host.rs, tests/e2e/v0/mod.rs, tests/e2e/v0/wasm.rs, tests/e2e/v1/func.rs, tests/spec/mod.rs, tests/spec/v0/run.rs, tests/spec/v1/context.rs, tests/spec/v1/error.rs, tests/spec/v1/run.rs
This PR entirely separates `wasmi` and `wasmi_v1` crates.
This removes the `v1` crate feature from `wasmi` again which also has the effect that our CI is simpler again.
Tests and benchmarks now operate without crate feature flags always on both `wasmi` and `wasmi_v1` crates.
=> Separate wasmi wasmi_v1 crates

wasmi_v1/src/global.rs, wasmi_v1/src/lib.rs, wasmi_v1/src/module/instantiate.rs
This add `GlobalType` to the `wasmi_v1` crate so that now all instance types (`Func`, `Table`, `Memory` and `Global`) do have some associated `XType`.
- `Func` -> `FuncType`
- `Table` -> `TableType`
- `Memory` -> `MemoryType`
- `Global` -> `GlobalType`
With this PR we also cleaned up the `InstantiationError` that was especially ugly due to the missing `GlobalType`.
=> Add GlobalType

.github/workflows/rust.yml
This PR can be used as the possible temporary fix until the project's dependencies will be able to compile on `windows-2022`.
=> CI: pin windows-latest to windows-2019

Cargo.toml, benches/bench/mod.rs, benches/benches.rs, src/lib.rs, src/module.rs, src/prepare/tests.rs, tests/e2e/v0/mod.rs, tests/e2e/v0/wasm.rs, wasmi_v1/Cargo.toml, wasmi_v1/src/module/tests.rs
This will further improve Wasm spec compliance once https://github.com/paritytech/wasmi/pull/346 lands.
The `wat` crate is authored by the BytecodeAlliance and in a much better shape than the `wabt` crate.
Also it is stlil maintained and updated for new Wasm proposals and fixes.
Remaining wabt users are:
- The two outdated fuzz systems.
- The outdated v0 Wasm testsuite.
=> Use wat instead of wabt crate where possible

core/src/nan_preserving_float.rs, core/src/trap.rs, core/src/value.rs, core/src/vmem.rs
This PR is a refinement of [this PR](https://github.com/paritytech/wasmi/pull/347).
The main difference between this PR and the former is that I only annotated relevant functions in the `wasmi_core` crate.
I verified with benchmarks that the best case performance is not regressed.
In fact benchmarks show some neat wins in performance even in the current best case profile settings.
```toml
[profile.release]
lto = "fat"
codegen-units = 1
```
<details>
```
compile_and_validate/v0 time:   [6.8221 ms 6.8453 ms 6.8721 ms]                                    
change: [-2.0524% -1.5869% -1.1425%] (p = 0.00 < 0.05)
Performance has improved.
Found 7 outliers among 100 measurements (7.00%)
1 (1.00%) low mild
2 (2.00%) high mild
4 (4.00%) high severe
compile_and_validate/v1 time:   [6.7297 ms 6.7463 …
```
=> Add #[inline] annotations to small functions in wasmi_core crate

core/src/lib.rs, core/src/value.rs, tests/spec/v1/mod.rs, wasmi_v1/src/engine/bytecode/mod.rs, wasmi_v1/src/engine/bytecode/visitor.rs, wasmi_v1/src/engine/code_map.rs, wasmi_v1/src/engine/exec_context.rs, wasmi_v1/src/engine/func_builder/mod.rs, wasmi_v1/src/module/compile/mod.rs, wasmi_v1/src/module/compile/operator.rs
Closes https://github.com/paritytech/wasmi/issues/355.
=> Support `non-trapping-float-to-int-conversions` Wasm proposal

README.md, tests/spec/local/missing-features/mutable-global-disabled.wast, tests/spec/local/missing-features/saturating-float-to-int-disabled.wast, tests/spec/local/missing-features/sign-extension-disabled.wast, tests/spec/v1/descriptor.rs, tests/spec/v1/mod.rs, wasmi_v1/Cargo.toml, wasmi_v1/src/engine/mod.rs, wasmi_v1/src/module/compile/mod.rs, wasmi_v1/src/module/parser.rs
This allows us to properly support the `mutable-globals`, `sign-extension-ops` and `saturating-float-to-int` Wasm proposals.
=> Update wasmparser: 0.82 -> 0.83

core/src/lib.rs, core/src/untyped.rs, wasmi_v1/src/engine/bytecode/mod.rs, wasmi_v1/src/engine/bytecode/visitor.rs, wasmi_v1/src/engine/exec_context.rs, wasmi_v1/src/engine/func_args.rs, wasmi_v1/src/engine/mod.rs, wasmi_v1/src/engine/value_stack.rs, wasmi_v1/src/func/into_func.rs
Closes https://github.com/paritytech/wasmi/issues/368.
Maybe we also want to support Wasm `load` and `store` operations but I have not yet come up with a decent API for those.
Also for completeness we could support `const` operations such as `i32.const`:
```rust
/// Executes `i32.const` Wasm operation.
pub fn i32_const(value: i32) -> Self {
Self::from(value)
}
```
Does not do a lot though.
Due to missing never-impls in Rust we have to move the `ReadParams` and `WriteResults` API from `wasmi_v1` into `wasmi_core`. This is actually nice since we were able to convert it into a more generic and reusable interface this way.
=> Implement UntypedValue in wasmi_core

core/src/untyped.rs
found while integrating new `UntypedValue` into https://github.com/paritytech/wasmi/pull/367.
=> fix From<float> impls for UntypedValue

Cargo.toml, cli/Cargo.toml, cli/src/main.rs, core/src/value.rs
Simple CLI tool to run `.wat` or `.wasm` files given a function name and parameters. Prints the results after execution.
This should improve accessibility of `wasmi` to new users, people who want to toy with it or developers who want to see how `wasmi` is to be used as a library.
=> Add cli tool to execute .wat or .wasm using wasmi_v1

core/src/untyped.rs
This caused for example that an i32 with value -1 would not be serialized as `0xFFFF_FFFF` (= `u32::MAX`) but rather as `u64::MAX`. This bug was discovered while debugging the `rf-register-machine-bytecode` branch.
=> Fix From<$signed_prim> impl for UntypedValue

.github/workflows/rust.yml, wasmi_v1/src/engine/func_builder/control_stack.rs, wasmi_v1/src/engine/func_builder/mod.rs, wasmi_v1/src/engine/func_builder/value_stack.rs, wasmi_v1/src/lib.rs, wasmi_v1/src/module/builder.rs, wasmi_v1/src/module/data.rs, wasmi_v1/src/module/element.rs, wasmi_v1/src/module/error.rs, wasmi_v1/src/module/export.rs, wasmi_v1/src/module/import.rs, wasmi_v1/src/module/mod.rs, wasmi_v1/src/module/parser.rs
... by placing it on a target without an operating system.
The test's scope is reduced from --workspace to --lib, as only that
component (and its transitive dependencies) are expected to be no_std.
Closes: https://github.com/paritytech/wasmi/issues/374
=> CI: Check that the no_std build is built without std

cli/Cargo.toml, cli/src/main.rs, wasmi_v1/src/lib.rs, wasmi_v1/src/module/export.rs, wasmi_v1/src/module/mod.rs
This PR makes the `wasmi_cli` use the popular `anyhow` crate for error reporting which improves printing of some errors.
Also `wasmi` CLI now shows all exported functions of a module in case the user given function could not be found.
=> Improve wasmi CLI

CHANGELOG.md, Cargo.toml, validation/Cargo.toml
This is going to be the first published `wasmi` release that uses the [`wasmi_core`](https://crates.io/crates/wasmi_core) crate.
=> Prepare for wasmi release v0.12

README.md, fuzz/Cargo.toml, fuzz/fuzz_targets/load.rs, fuzz/fuzz_targets/load_spec.rs, fuzz/fuzz_targets/load_wabt.rs, fuzz/fuzz_targets/load_wasmparser.rs
For some reason fuzz didn't work:
```
WARNING: Failed to find function "__sanitizer_get_total_unique_coverage".
WARNING: Failed to find function "__sanitizer_reset_coverage".
INFO: Seed: 3860000992
ERROR: __sanitizer_reset_coverage is not defined. Exiting.
Did you use -fsanitize-coverage=... to build your code?
────────────────────────────────────────────────────────────────────────────────
Error: Fuzz target exited with exit status: 1
```
I fixed it and found bugs:
1)
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
left: `true`,
right: `false`', fuzz_targets/load_wabt.rs:10:5
Output of `std::fmt::Debug`:
[0, 97, 115, 109, 1, 0, 0, 0, 12, 1, 11]
```	
Which means `wasmi` accepts a code which is not accepted by `wabt`. To try a .wasm file: `echo AGFzbQEAAAAMAQA= | …
=> Make fuzz work

CHANGELOG.md, README.md, wasmi_v1/Cargo.toml
Wasmi version was 0.11 before because the latest release was with the legacy wasmi engine and we forgot to synchronize versions until then.
=> wasmi: bump version to 0.14

core/src/trap.rs, core/src/untyped.rs, core/src/value.rs, wasmi_v1/src/engine/exec_context.rs, wasmi_v1/src/engine/value_stack.rs
Today I was casually profiling `wasmi` and found that the `ValueStack` was particularly hot even though it has already seen many optimizations. So I took the chance and optimized it further given the invariants during bytecode execution.
The results are approx. 10% performance improvement across the board.
The optimizations along the way:
- Removed some unnecessary bounds checks in `ValueStack`.
- Applied `#[cold]` to `UntypedError::invalid_len()` error constructor.
- Avoid adding and subtracting 1 for each `local.{get,set,tee}` depth.
- Simplify code for `{i32,i64}.{div,rem}`.
=> Optimize ValueStack

.gitignore, wasmi_v1/fuzz/Cargo.toml, wasmi_v1/fuzz/fuzz_targets/translate.rs
This is a very naive fuzz testing framework based on the BytecodeAlliance's `wasm-smith` tool.
It currently only fuzz tests Wasm parsing, validation and translation to `wasmi`'s internal bytecode.
In later revisions we want to add fuzz testing for execution as well.
However, this requires a proper baseline Wasm execution engine that we can use to compare `wasmi` against.
For this the BytecodeAlliance's Wasm spec interpreter is the best candidate but it is lacking a proper Rust crate and just lives inside of the Wasmtime repository as of now. This might change in the future.
We want to merge this PR because it is currently a major headache to work in difference feature branches with all of the fuzz testing artifacts around.
=> Add initial naive fuzz testing based on wasm-smith

core/src/host_error.rs, core/src/trap.rs, wasmi_v1/benches/benches.rs, wasmi_v1/tests/spec/run.rs
This PR refactors the `wasmi_core` `Trap` type to have a `size_of` equal to a pointer type.
Benchmarks show that this improves performance across the board especially for call intense workloads which was to be expected by roughly 5-7%.
=> Refactor Trap to be of pointer size

wasmi_v1/src/module/read.rs
Currently behavior is panicking.
=> Fix the read implementation on no-std

wasmi_v1/src/engine/func_builder/control_stack.rs, wasmi_v1/src/engine/func_builder/inst_builder.rs, wasmi_v1/src/engine/func_builder/locals_registry.rs, wasmi_v1/src/engine/func_builder/mod.rs, wasmi_v1/src/engine/func_builder/value_stack.rs, wasmi_v1/src/engine/mod.rs, wasmi_v1/src/module/compile/mod.rs, wasmi_v1/src/module/compile/operator.rs, wasmi_v1/src/module/parser.rs
This PR allows to reuse allocations of `FunctionBuilder` between different Wasm function translation units.
Benchmarks show an improvement in compilation time by ~10%.
=> Reuse func builder allocations

wasmi_v1/benches/bench/mod.rs, wasmi_v1/src/engine/bytecode/mod.rs, wasmi_v1/src/engine/cache.rs, wasmi_v1/src/engine/code_map.rs, wasmi_v1/src/engine/config.rs, wasmi_v1/src/engine/exec_context.rs, wasmi_v1/src/engine/mod.rs, wasmi_v1/src/engine/stack/frames.rs, wasmi_v1/src/engine/stack/mod.rs, wasmi_v1/src/engine/stack/values.rs, wasmi_v1/src/engine/value_stack.rs, wasmi_v1/src/instance.rs, wasmi_v1/src/lib.rs, wasmi_v1/src/module/parser.rs, wasmi_v1/tests/spec/mod.rs
This PR heavily refactors the `v1` `wasmi` engine.
Greatly reorganizes the engine codebase and cleans up some older parts.
This results in up to 16% performance wins for call intense workloads.
Also the call stack now demands less memory for the same amount of nested calls.
Caching of instance related data now works across function call boundaries.
=> v1: Optimize calls

wasmi_v1/src/engine/cache.rs, wasmi_v1/src/engine/exec_context.rs, wasmi_v1/src/engine/mod.rs
This PR improves the existing `InstanceCache` to also cache the underlying bytes of the default linear memory to avoid an indirection for every consecutive `load` and `store` operation. Special care must be taken when the linear memory might be invalidated through host calls or `memory.grow` operations.
According to our benchmarks this yields a performance improvement in many benchmarks between 5-8%, especially for the memory intense work loads.
A few call intense work loads slightly regressed in the range of 2-3%.
=> Cache default linear memory bytes

wasmi_v1/src/engine/bytecode/mod.rs, wasmi_v1/src/engine/exec_context.rs, wasmi_v1/src/engine/func_builder/mod.rs
- `GetLocal` -> `LocalGet`
- `SetLocal` -> `LocalSet`
- `TeeLocal` -> `LocalTee`
- `GetGlobal` -> `GlobalGet`
- `SetGlobal` -> `GlobalSet`
- `CurrentMemory` -> `MemorySize`
- `GrowMemory` -> `MemoryGrow`
=> rename some wasmi instructions

wasmi_v1/benches/benches.rs, wasmi_v1/benches/wat/global_bump.wat, wasmi_v1/src/engine/exec_context.rs, wasmi_v1/src/global.rs
Currently the `global.get` and especially `global.set` perform a lot of unnecessary conversions and checks.
For example `global.set` checks for global variable mutability and checks types even though that has already been done during Wasm validation at the time of `wasmi` bytecode execution.
This also adds a new benchmark to test global variable `set` and `get` performance and shows a roughly 17% performance boost.
=> Optimize `global.get` and `global.set` execution

wasmi_v1/src/engine/cache.rs, wasmi_v1/src/engine/executor.rs, wasmi_v1/src/global.rs
The `global_bump` benchmark shows an 25% performance improvement with this optimization.
=> Optimize `global.get` and `global.set` by caching global variable value pointer

core/Cargo.toml, core/src/value.rs, wasmi_v1/Cargo.toml, wasmi_v1/benches/benches.rs, wasmi_v1/benches/wat/trunc_f2i.wat
According to our new benchmarks this optimization improves performance of all 8 float to int Wasm truncation instructions by roughly 6000% (a.k.a. 60 times faster).
This also gets us rid of the `num-rational` crate dependency from `wasmi_core` which reduces `wasmi` fresh release build time by roughly 23% and reduces Wasm file size of `wasmi_core` crate by roughly 5%.
Nuff said ...
=> Optimize float-to-int Wasm trunc instructions

wasmi_v1/src/engine/func_builder/mod.rs
This causes less strain on the heap allocator for Wasm binaries with many `br_table` instructions.
=> Reuse allocations for `br_table` translations

.github/dependabot.yml, .github/workflows/rust.yml
This PR bumps GHA versions to current ones.
Also added `dependabot.yml` to get notified about GHA updates automatically.
@Robbepop Do you want to add `cargo` versions monitoring to dependabot?
Releated issues https://github.com/paritytech/ci_cd/issues/464 https://github.com/paritytech/ci_cd/issues/407
=> [ci] bump gha versions and add dependabot

wasmi_v1/src/memory/mod.rs, wasmi_v1/src/store.rs
Solves https://github.com/paritytech/wasmi/issues/447
=> Add `Memory::data_and_store_mut`

.gitlab-ci.yml
This PR changes GitLab runners where benchmarks will be executed on. Those `linux-docker-bench` runners specially tuned to have only 1 active job running at a time so must provide more trustworthy results
=> ci change gitlab runner for benchmarking

wasmi_v1/src/engine/executor.rs, wasmi_v1/src/engine/mod.rs
Locally this displayed some slight improvements in some call intense workloads whereas the `global_bump` benchmarks locally showed slight regression. Let's see what our GitLab runners are having to say.
Generally though this PR is not an optimization PR but rather a cleanup of the executor.
=> Cleanup Engine

wasmi_v1/src/engine/func_builder/mod.rs, wasmi_v1/src/engine/func_builder/visit.rs, wasmi_v1/src/module/compile/mod.rs, wasmi_v1/src/module/mod.rs, wasmi_v1/src/module/parser.rs
This is an experiment to see whether the move overhead of storing reusable allocations by value outweights the indirection overhead of accessing them via reference. Locally I see no significant change in performance, however, so far it seems that the access via reference is by far simpler to setup and use and produces slightly more readable code imo.
These changes might also make it simpler to implement parallel parsing, validation and translation in future versions of `wasmi`. That means that all functions are parsed, validated and translated in parallel isolation. So far `wasmi` does not support parallel translation of functions since `wasmi` is primarily used by us as Wasm binary and Wasm does not (yet) support parallelism.
=> Inline reusable allocations

crates/wasmi/src/engine/code_map.rs, crates/wasmi/src/engine/executor.rs, crates/wasmi/src/engine/mod.rs, crates/wasmi/src/engine/stack/frames.rs, crates/wasmi/src/engine/stack/mod.rs
Closes https://github.com/paritytech/wasmi/issues/479.
=> Add `InstructionPtr` abstraction (take 2)

.gitlab-ci.yml, scripts/ci/benchmarks-report.sh
Addresses https://github.com/paritytech/wasmi/issues/486
PR adds column to the benchmarks report with details about wasmtime vs native overhead.
=> CI: Add wasmtime overhead status to the report

.gitlab-ci.yml, scripts/ci/benchmarks-report.sh
Closes https://github.com/paritytech/wasmi/issues/488
Squeezes benchmark report table horizontally by wrapping benchmark name
=> CI: Wrap benchmark name to reduce horizontal size of the report table

crates/wasmi/src/engine/executor.rs, crates/wasmi/src/engine/stack/values/vref.rs
This is a result of an observation that we could speed-up execution of branch and return instructions that keep no values or just a single value upon jump. Especially in the Wasm MVP those two cases are the common ones.
This is take 2 after the first experiment yielded really bad results: https://github.com/paritytech/wasmi/pull/492
=> Optimize for common `drop_keep` cases in `wasmi` executor

.gitlab-ci.yml
Cleanup `target/wasm32-wasi` dir before benchmarking PR branch to prevent artifact copying errors.
=> CI: cleanup wasm32 target dir before pr benchmark

crates/wasmi/benches/benches.rs, crates/wasmi/src/func/into_func.rs, crates/wasmi/src/func/mod.rs, crates/wasmi/src/lib.rs, crates/wasmi/tests/e2e/v1/func.rs
- Makes `IntoFunc`, `WasmType` and `WasmRet` public.
- Removes generic `ctx: S` parameter from `Func::typed` constructor.
- Adds missing `Result<T, Trap>: WasmRet` impl.
- Also adds unit tests to assert that those impls exist.
- Added `#[inline]` to some trivial method impls.
=> Fix `IntoFunc` API

.gitlab-ci.yml
Sometimes CI fails due to ad hoc network issues like here https://gitlab.parity.io/parity/mirrors/wasmi/-/jobs/1940274 which can be fixed just by restarting job. And we have such setting in place - [`retry`](https://docs.gitlab.com/ee/ci/yaml/#retry) block, but for some reason GitLab fails to match above mentioned events to `when` rules `runner_system_failure`, `unknown_failure`, `api_failure`
This PR introduces functionality to make 2 additional attempts in case if CI job fails. Use default `when: always` implicitly.
=> CI: retry CI twice on every type of failure

.github/workflows/rust.yml
Due to use of `unsafe` Rust it is useful to have `miri` testing for the `wasmi` workspace.
Unfortunately this does not (yet) test the extensive Wasm spec test suite but runs only the library unit tests of the entire workspace.
We might be required to either refactor how the Wasm spec test suite works or add some execution unit tests.
=> CI: add `miri` check

.github/workflows/rust.yml, crates/wasmi/src/engine/code_map.rs
- As reported by `miri` when testing for `--doc` tests.
- We cannot use `NonNull` there since `NonNull` is missing the respective `offset` method, yet, as discussed and requested here: https://github.com/rust-lang/rust/issues/72429
- This PR also adds a `miri --doc` CI test run since that is how we discovered this potential UB.
=> Fix potential UB

crates/wasmi/src/engine/func_builder/locals_registry.rs, crates/wasmi/src/engine/func_builder/mod.rs, crates/wasmi/src/engine/func_builder/value_stack.rs
Due to historical reasons the `wasmi` codegen that converts from Wasm bytecode to its internal `wasmi` bytecode still performed many checks that have already been covered by the `wasmparser` based Wasm validation.
This PR eliminates all or most of those unnecessary duplicate checks for some reasonable speedups in translation time.
Locally I was able to see roughly 15% speedup in the translation benchmark.
In detail this PR
- Removes the emulated `ValueStack` during translation time and replaces it with a glorified `ValueStackHeight` counter.
- Simplifies the `LocalsRegistry` to no longer deal with local variable types so that it also became a glorified counter.
- Removes tons of type checks during translation time. These are unnecessary since the Wasm validation already performs them.
=> Simplify and optimize `wasmi` codegen

crates/wasmi/src/global.rs, crates/wasmi/src/instance.rs, crates/wasmi/src/linker.rs, crates/wasmi/src/module/instantiate/error.rs, crates/wasmi/src/module/instantiate/mod.rs, crates/wasmi/src/module/instantiate/pre.rs, crates/wasmi/src/module/mod.rs
- Preallocates buffers upon Module instantiation to reduce amount of copying and reallocations.
- Uses more dense data structures for `Instance`, e.g. `Box<[T]>` instead of `Vec<T>` or `Box<str>` instead of `String`.
- Removes lifetime parameter from `InstancePre`.
- No longer copies over the contents of the `Module`'s `func_types` upon instantiation but efficiently clones via ref counting.
=> Refactor, cleanup and optimize Wasm module instantiation

crates/wasmi/src/func_type.rs
We might also want to move the `FuncType` definition into the `wasmi_core` crate for reusability once we split up the workspace into many more smaller crates.
=> Cleanup some test code

crates/core/src/value.rs, crates/wasmi/src/lib.rs, crates/wasmi/src/module/global.rs, crates/wasmi/src/module/mod.rs
And do code fmt for traits impl orders.
=> refactor: minor improve and remove unused traits impls for f32/f64

crates/core/src/host_error.rs, crates/core/src/lib.rs, crates/core/src/trap.rs, crates/core/src/value.rs, crates/wasmi/benches/benches.rs, crates/wasmi/src/engine/cache.rs, crates/wasmi/src/engine/executor.rs, crates/wasmi/tests/spec/run.rs
Closes https://github.com/paritytech/wasmi/issues/517.
Unblocks https://github.com/paritytech/wasmi/pull/557.
=> Refactor `wasmi_core::Trap` and make it more similar to Wasmtime's `Trap`

crates/wasi/Cargo.toml, crates/wasi/src/guest_memory.rs, crates/wasi/src/lib.rs, crates/wasi/src/snapshots/preview_1.rs
Closes https://github.com/paritytech/wasmi/issues/561.
Unfortunately `wiggle` version `1.0.2` is the most recent version that is Wasm runtime agnostic. All later major `wiggle` versions starting with `wiggle` version `2.0.0` and up and therefore also all later `wasi-common` version (since `wasi-common` builds on top of `wiggle`) are directly depending on Wasmtime.
Therefore a downgrade from version `2.0.0` to version `1.0.0` was necessary to fix this issue for `wasmi`.
In the long run we (`wasmi` team) might have to ship our own WASI implementation or find an alternative solution since we do not want us to depend on Wasmtime or any other Wasm runtime.
=> Remove Wasmtime dependency from `wasmi_wasi` crate

crates/arena/src/lib.rs, crates/wasmi/src/engine/code_map.rs, crates/wasmi/src/store.rs
Closes https://github.com/paritytech/wasmi/issues/565.
=> Make `Store` `Send` and `Sync`

crates/wasi/Cargo.toml
Wiggle 2.0 still allows removing wasmtime dependencies.
The one in the main branch of wasmtime repo doesn't allow removing it, but it is v4.0. I'll open an issue about that.
Bonus: fixes #564
=> Use wiggle 2.0.

crates/wasmi/src/lib.rs, crates/wasmi/src/module/mod.rs
If we want to create stub function, we must need to know the imports info.
I think substrate also need this method to do `prepare_import` like wasmtime.
=> feat: make Module::imports be `pub`

crates/wasi/src/lib.rs
The former is re-exported from `cap-std`, which is the type used in `preopen_dir`, while the latter is the internal type of `wasi_cap_std_sync`. This change follows the behavior of `wasmtime-wasi`, and will reduce users' works on managing imports.
https://github.com/bytecodealliance/wasmtime/blob/main/crates/wasi/src/lib.rs#L15-L24
=> Import `wasi_cap_std_sync::Dir` instead of `wasi_cap_std_sync::dir::Dir`.

.github/workflows/rust.yml, crates/cli/src/main.rs
Before this change users had to provide a non-existing func name in order for the `wasmi` CLI to print out all exported function names such as `wasmi_cli fibonacci.wat foo`.
```
> wasmi_cli fibonacci.wat
Error: missing function name argument for fibonacci.wat
The Wasm module exports the following functions:
- fn fib_recursive(i64) -> i64
- fn fib_iterative(i64) -> i64
```
=> Make `wasmi` CLI print exported functions if `func_name` arg is missing

crates/wasmi/src/engine/func_types.rs, crates/wasmi/src/linker.rs, crates/wasmi/src/module/instantiate/error.rs, crates/wasmi/src/module/instantiate/mod.rs, crates/wasmi/src/module/mod.rs
From what I understand about the sparse description of the issue this PR closes https://github.com/paritytech/wasmi/issues/581.
=> Make `Module::imports` iterator return `FuncType` instead of `DedupFuncType`

crates/wasi/src/lib.rs
According to [docs](https://docs.rs/ambient-authority/latest/ambient_authority/), this function should be exported.
It is used when preopening a folder with `Dir::open_ambient_dir`.
=> Re-export ambient_authority.

crates/wasmi/src/module/instantiate/mod.rs, crates/wasmi/src/module/instantiate/tests.rs, crates/wasmi/src/module/mod.rs
Closes https://github.com/paritytech/wasmi/issues/587.
Thanks @yjhmelody for reporting the issue.
=> Fix duplicated imported linear memories and tables

crates/wasmi/src/engine/traits.rs
The return value was never used and thus can be removed. This may improve performance.
Maybe this micro optimizes certain use cases. (experiment)
=> Return `()` from `CallResults` for slices

crates/wasmi/src/engine/mod.rs, crates/wasmi/src/engine/resumable.rs, crates/wasmi/src/func/mod.rs, crates/wasmi/src/func/typed_func.rs, crates/wasmi/src/lib.rs, crates/wasmi/tests/e2e/v1/resumable_call.rs
So far the resumable calls feature was only available for the untyped `Func` type but not the statically typed `TypedFunc` type.
The reason for this was non-technical and therefore this follow-up PR adds this missing functionality.
The PR also simplifies the API for `Func::call_resumable` a bit and slightly improves docs.
=> Implement resumable calls for `TypedFunc`

crates/core/src/untyped.rs, crates/wasmi/src/engine/cache.rs, crates/wasmi/src/engine/executor.rs
Nearly all other Wasm operations are already included in the `UntypedValue` API but `store` and `load` operations were still missing. This will help to reduce code duplication especially if more `wasmi` engine backends and routines are added over time. Also this shifts some code from the bloated `wasmi` crate over to the more lightweight `wasmi_core` crate.
=> Add Wasm load and store API to `UntypedValue`

crates/wasmi/src/store.rs
This might be useful to make the engine's executor non-generic. A non-generic engine executor is important to decrease bloat but also to make use of the experimental `#[union_fn]` data structure.
=> Create a non-generic `StoreInner`

crates/arena/src/component_vec.rs, crates/arena/src/lib.rs, crates/wasmi/src/engine/cache.rs, crates/wasmi/src/engine/executor.rs, crates/wasmi/src/engine/mod.rs, crates/wasmi/src/global.rs, crates/wasmi/src/instance.rs, crates/wasmi/src/lib.rs, crates/wasmi/src/module/instantiate/tests.rs, crates/wasmi/src/store.rs
This PR technically prepares `wasmi` for using the new `#[union_fn]` macro.
Before this PR the `Engine` executor was generic over a `ctx: impl AsContextMut` which is no longer required since the `Engine` executor now works given a non-generic `&mut StoreInner`. The `StoreInner` is a non-generic abstraction of the `Store<T>` type which holds all the data that is not associated to the `T` in `Store<T>`.
=> Make `Engine`'s executor use `&mut StoreInner` (making it non-generic)

CHANGELOG.md, crates/cli/src/main.rs, crates/core/src/value.rs, crates/wasmi/src/engine/executor.rs, crates/wasmi/src/engine/func_builder/mod.rs, crates/wasmi/src/engine/mod.rs, crates/wasmi/src/engine/resumable.rs, crates/wasmi/src/engine/stack/mod.rs, crates/wasmi/src/engine/traits.rs, crates/wasmi/src/external.rs, crates/wasmi/src/func/mod.rs, crates/wasmi/src/func/typed_func.rs, crates/wasmi/src/func_type.rs, crates/wasmi/src/global.rs, crates/wasmi/src/linker.rs, crates/wasmi/src/memory/mod.rs, crates/wasmi/src/module/instantiate/error.rs, crates/wasmi/src/module/instantiate/mod.rs, crates/wasmi/src/module/utils.rs, crates/wasmi/src/store.rs, crates/wasmi/src/table.rs, crates/wasmi/tests/e2e/v1/resumable_call.rs, crates/wasmi/tests/spec/context.rs
Follow-up for https://github.com/paritytech/wasmi/pull/615.
=> Improve Wasmtime-like API for `wasmi` further

CHANGELOG.md, crates/wasmi/src/module/builder.rs, crates/wasmi/src/module/export.rs, crates/wasmi/src/module/instantiate/mod.rs, crates/wasmi/src/module/mod.rs, crates/wasmi/src/module/parser.rs
This API was still missing since it is available in the Wasmtime API.
=> Implement `Module::get_export` method

CHANGELOG.md, crates/wasmi/src/lib.rs, crates/wasmi/src/module/builder.rs, crates/wasmi/src/module/compile/mod.rs, crates/wasmi/src/module/data.rs, crates/wasmi/src/module/element.rs, crates/wasmi/src/module/export.rs, crates/wasmi/src/module/global.rs, crates/wasmi/src/module/import.rs, crates/wasmi/src/module/init_expr.rs, crates/wasmi/src/module/utils.rs
Now `ModuleError` lives under `crate::errors` just like all other error types.
=> Remove `ModuleError` export from crate root

crates/wasmi/src/memory/mod.rs, crates/wasmi/src/module/instantiate/error.rs, crates/wasmi/tests/spec/mod.rs, crates/wasmi/tests/spec/run.rs
If the Wasm spec test suite expects a trap, then the trap message no longer has to fully match the expected trap message. Instead it now only has to start with the exact same characters. This allows for `wasmi` to provide more information to users and still kind of abide to the general expected trap messages.
Also this PR adds tests from the `mutable-global` Wasm proposal and introduces a temporary fix for the long standing `linking` test failure. This temporary fix will be gone when `wasmi` implements the `bulk-memory` Wasm proposal.
=> Clean-up and improve Wasm spec test

crates/wasmi/src/engine/cache.rs, crates/wasmi/src/engine/executor.rs, crates/wasmi/src/engine/func_types.rs, crates/wasmi/src/engine/mod.rs, crates/wasmi/src/engine/stack/frames.rs, crates/wasmi/src/engine/stack/mod.rs, crates/wasmi/src/engine/tests.rs, crates/wasmi/src/func/caller.rs, crates/wasmi/src/func/mod.rs, crates/wasmi/src/global.rs, crates/wasmi/src/instance.rs, crates/wasmi/src/memory/mod.rs, crates/wasmi/src/module/builder.rs, crates/wasmi/src/module/compile/block_type.rs, crates/wasmi/src/module/instantiate/tests.rs, crates/wasmi/src/module/mod.rs, crates/wasmi/src/store.rs, crates/wasmi/src/table.rs
The idea behind this change is that the Rust compiler (and LLVM) have a greater chance to apply optimizations if parameters are at most pointer sized. Unfortunately `wasmi` reference types such as `Func`, `Global` etc. do eventually not fit into a pointer and therefore might regress performance.
Furthermore this is more aligned with what the Wasmtime API does in such cases.
As an additional bonus this allows us to more room for experimentation with the internals of those `wasmi` reference types such as `Func`, `Global` etc. since `wasmi` methods are less dependent on the actual structure of those types with these changes.
=> Use references where possible in `Store` and `StoreInner`

crates/arena/src/lib.rs, crates/core/src/trap.rs, crates/core/src/value.rs, crates/wasmi/src/element.rs, crates/wasmi/src/engine/bytecode/mod.rs, crates/wasmi/src/engine/executor.rs, crates/wasmi/src/engine/func_builder/mod.rs, crates/wasmi/src/externref.rs, crates/wasmi/src/func/mod.rs, crates/wasmi/src/linker.rs, crates/wasmi/src/memory/mod.rs, crates/wasmi/src/module/builder.rs, crates/wasmi/src/module/element.rs, crates/wasmi/src/module/init_expr.rs, crates/wasmi/src/module/instantiate/mod.rs, crates/wasmi/src/module/mod.rs, crates/wasmi/src/store.rs, crates/wasmi/src/table.rs, crates/wasmi/src/value.rs, crates/wasmi/tests/spec/context.rs, crates/wasmi/tests/spec/run.rs
Closes https://github.com/paritytech/wasmi/issues/496.
=> Implement `reference-types` Wasm proposal

crates/wasmi/src/func/into_func.rs
This allows to use `FuncRef` and `ExternRef` types with the `TypedFunc` API and everything that connects to it.
This functionality was trivial to add and simply forgotten in the `reference-types` Wasm proposal implementation PR.
=> Impl `WasmType` for `FuncRef` and `ExternRef`

crates/core/src/trap.rs
- `Trap` no longer is `Clone`
- Added `Trap::{downcast_mut, downcast}` methods
=> Refactor `Trap` type

crates/wasmi/src/engine/func_args.rs, crates/wasmi/src/func/into_func.rs, crates/wasmi/src/func/mod.rs, crates/wasmi/tests/e2e/v1/func.rs
Closes https://github.com/paritytech/wasmi/issues/658.
cc @tomaka
=> Add `Func::new` constructor

crates/cli/src/args.rs, crates/cli/src/main.rs
=> `wasmi_cli`: Properly forward WASI arguments

.github/workflows/rust.yml, crates/core/Cargo.toml
According to [this blog post](https://ectobit.com/blog/speed-up-github-actions-rust-pipelines/) this should speed up the CI a bit.
This reduced the time for the `test` runs from 8-10 minutes down to 2-3 minutes on both Windows and MacOS targets.
Also it reduced build time for the `build` run from 1 minute to 40 seconds.
=> CI: Use Cargo cache for GitHub Actions

crates/wasmi/src/engine/stack/mod.rs, crates/wasmi/tests/e2e/v1/resumable_call.rs
Fixes bug encountered in this GitHub PR: https://github.com/smol-dot/smoldot/pull/18.
=> Fix resumable calls bug found in smoldot

CHANGELOG.md, crates/cli/Cargo.toml, crates/wasi/Cargo.toml, crates/wasmi/Cargo.toml, crates/wasmi/src/engine/config.rs
Unblocking https://github.com/smol-dot/smoldot/pull/18.
=> Prepare `wasmi` release version `0.26.1`

crates/wasmi/src/engine/executor.rs, crates/wasmi/src/error.rs, crates/wasmi/src/func/caller.rs, crates/wasmi/src/lib.rs, crates/wasmi/src/memory/mod.rs, crates/wasmi/src/store.rs
Fuel checks are still happening before the bulk operation execution but fuel charging only happens if those operations succeeded.
This make sense given that all of these bulk operations fail fast. So only if they succeeded they actually performed a lot of potential computation.
This affects the following Wasm bulk operations:
- `memory.grow`: Already implemented deferred fuel charging but this implementation improves upon it.
- `memory.fill`
- `memory.copy`
- `data.init`
- `table.grow`
- `table.fill`
- `table.copy`
- `elem.init`
=> Defer charging fuel for bulk `table` and bulk `memory` operations

crates/cli/src/args.rs, crates/cli/src/main.rs
Closes https://github.com/paritytech/wasmi/issues/675.
cc @yamt
=> `wasmi_cli`: Preserve WASI exit status and other minor improvements

crates/cli/src/context.rs, crates/wasi/tests/wasi_wat.rs, crates/wasmi/benches/bench/mod.rs, crates/wasmi/benches/benches.rs, crates/wasmi/src/engine/mod.rs, crates/wasmi/src/engine/stack/frames.rs, crates/wasmi/src/engine/tests.rs, crates/wasmi/src/func/mod.rs, crates/wasmi/src/lib.rs, crates/wasmi/src/linker.rs, crates/wasmi/src/module/instantiate/tests.rs, crates/wasmi/src/store.rs, crates/wasmi/tests/e2e/v1/fuel_metering.rs, crates/wasmi/tests/e2e/v1/host_calls_wasm.rs, crates/wasmi/tests/e2e/v1/resumable_call.rs, crates/wasmi/tests/spec/context.rs
=> Refactor `Linker` for preparation of `Linker::func_{wrap,new}` methods

crates/wasmi/src/linker.rs
Closes https://github.com/paritytech/wasmi/issues/663.
cc @flavio
=> Add support for `Linker` defined host functions

crates/wasmi/src/engine/bytecode/utils.rs, crates/wasmi/src/engine/config.rs, crates/wasmi/src/engine/executor.rs, crates/wasmi/src/engine/func_builder/mod.rs, crates/wasmi/src/engine/func_builder/translator.rs, crates/wasmi/src/engine/tests.rs, crates/wasmi/src/module/compile/mod.rs, crates/wasmi/tests/e2e/v1/fuel_metering.rs
Closes https://github.com/paritytech/wasmi/issues/701.
=> Normalize fuel costs to roughly 1 fuel per executed instruction

crates/wasmi/src/engine/bytecode/mod.rs, crates/wasmi/src/engine/code_map.rs, crates/wasmi/src/engine/executor.rs, crates/wasmi/src/engine/func_builder/inst_builder.rs, crates/wasmi/src/engine/func_builder/mod.rs, crates/wasmi/src/engine/func_builder/translator.rs, crates/wasmi/src/engine/mod.rs, crates/wasmi/src/engine/tests.rs, crates/wasmi/src/func/mod.rs, crates/wasmi/src/module/builder.rs, crates/wasmi/src/module/compile/mod.rs, crates/wasmi/src/module/mod.rs, crates/wasmi/src/module/parser.rs
Closes https://github.com/paritytech/wasmi/issues/711.
=> Optimization: differentiate function calls

crates/wasmi/Cargo.toml, crates/wasmi/src/engine/const_pool.rs, crates/wasmi/src/engine/executor.rs
This allows us to remove `intx` dependency. This was an oversight in a previous PR.
=> make `ConstRef` based on `u32` instead of `intx::U24`

crates/core/src/trap.rs, crates/wasmi/src/engine/executor.rs, crates/wasmi/src/engine/mod.rs, crates/wasmi/src/func/typed_func.rs, crates/wasmi/src/lib.rs, crates/wasmi/src/limits.rs, crates/wasmi/src/linker.rs, crates/wasmi/src/memory/error.rs, crates/wasmi/src/memory/mod.rs, crates/wasmi/src/module/instantiate/error.rs, crates/wasmi/src/module/instantiate/mod.rs, crates/wasmi/src/store.rs, crates/wasmi/src/table/error.rs, crates/wasmi/src/table/mod.rs, crates/wasmi/tests/e2e/v1/mod.rs, crates/wasmi/tests/e2e/v1/resource_limiter.rs
Closes https://github.com/paritytech/wasmi/issues/728.
This implements the `wasmtime` `ResourceLimiter` API, as discussed in bug https://github.com/paritytech/wasmi/issues/728 .
Current limitations, caveats and points to discuss/review:
- ~Missing tests~
- ~Missing docs~
- ~Missing convenience types `StoreLimits` and `StoreLimitsBuilder`~
- To keep `#[derive(Debug)]` working I had to add a couple wrapper types.
- ~As much as possible, I tried to track `wasmtime`'s implementation: the `{instance,memory,table}_{count,limit}` fields, the `Store::bump_resource_counts` method, the `limits.rs` file, the global defaults returned from the default methods, etc. etc. This all feels like a fairly weird design to me (information cached or returned from multiple places) but I figured you'd prefer to …
=> Support for `ResourceLimiter` API

crates/wasmi/src/engine/bytecode/mod.rs, crates/wasmi/src/engine/bytecode/utils.rs, crates/wasmi/src/engine/executor.rs, crates/wasmi/src/engine/func_builder/translator.rs
This is an optimization for certain constant `f64` values that can losslessly be encoded as 32-bit `f32` values. This way we can avoid allocating `ConstRef` for many common cases.
=> Add `F64Const32` instruction

crates/wasmi/src/externref.rs, crates/wasmi/src/func/funcref.rs, crates/wasmi/src/lib.rs, crates/wasmi/src/reftype.rs
It is now based on `u64` instead of `UntypedValue` directly which makes more sense since `u64` is a more stable type and `UntypedValue` will likely change in the future, for example with the addition of the Wasm 128-bit SIMD proposal.
Also now both `FuncRef` and `ExternRef` share the same `Transposer` type.
=> Refactor `reftype` `Transposer` conversion utility

.github/workflows/publish-benchmarks.yml, .github/workflows/rust.yml, .gitlab-ci.yml, scripts/ci/sync_wait.sh
PR adds gitlab and github jobs that run benchmarks for master and create nice graphs that can be found [here](https://paritytech.github.io/wasmi/benchmarks/)
close https://github.com/paritytech/ci_cd/issues/848
=> Publishing benchmarks for graphs

crates/wasmi/src/engine/regmach/bytecode/utils.rs, crates/wasmi/src/engine/regmach/tests/op/call/indirect.rs, crates/wasmi/src/engine/regmach/tests/op/return_call/indirect.rs, crates/wasmi/src/engine/regmach/translator/instr_encoder.rs, crates/wasmi/src/engine/regmach/translator/stack/mod.rs, crates/wasmi/src/engine/regmach/translator/visit.rs
Closes #768.
This bug (issue #768) occurred when the call parameters needed to be copied over to a contiguous span in the dynamic register space and at the same time overwriting the index register. The fix is to simply copy the index register to a protected register when detecting this situation.
=> Fix `[return_]call_indirect` miscompilation

crates/wasmi/src/engine/executor.rs, crates/wasmi/src/engine/regmach/executor/instrs/call.rs
This avoids updating the instruction pointer of the current call frame upon a tail call since this call frame is going to be discarded upon a tail call.
=> Avoid updating `instr_ptr` for tail calls

crates/wasmi/Cargo.toml, crates/wasmi/src/engine/regmach/tests/op/local_set.rs, crates/wasmi/src/engine/regmach/translator/stack/provider.rs, crates/wasmi/src/engine/regmach/translator/stack/register_alloc.rs
Closes https://github.com/paritytech/wasmi/issues/766
This fixes a bug in preservation of `local.set` for local variables that have been pushed multiple times onto the stack upon preservation and implements recycling of preservation slots to reduce register pressure.
=> Refactor `local.set` register preservation

crates/wasmi/src/engine/func_builder/inst_builder.rs, crates/wasmi/src/engine/regmach/tests/op/local_set.rs, crates/wasmi/src/engine/regmach/translator/instr_encoder.rs, crates/wasmi/src/engine/regmach/translator/visit.rs
Closes https://github.com/paritytech/wasmi/issues/765
=> Allow `local.set` optimization with active preservation

crates/wasmi/src/engine/regmach/bytecode/construct.rs, crates/wasmi/src/engine/regmach/bytecode/mod.rs, crates/wasmi/src/engine/regmach/bytecode/utils.rs, crates/wasmi/src/engine/regmach/executor/instrs.rs, crates/wasmi/src/engine/regmach/executor/instrs/branch.rs, crates/wasmi/src/engine/regmach/tests/op/block.rs, crates/wasmi/src/engine/regmach/tests/op/br_if.rs, crates/wasmi/src/engine/regmach/tests/op/cmp_br.rs, crates/wasmi/src/engine/regmach/tests/op/if_.rs, crates/wasmi/src/engine/regmach/translator/instr_encoder.rs, crates/wasmi/src/engine/regmach/translator/relink_result.rs, crates/wasmi/src/engine/regmach/translator/visit_register.rs
Closes https://github.com/paritytech/wasmi/issues/800.
=> Remove superseeded conditional branch instructions

.github/workflows/rust.yml, crates/wasmi/src/engine/mod.rs, crates/wasmi/src/engine/regmach/executor/instrs.rs, crates/wasmi/src/engine/regmach/executor/instrs/call.rs, crates/wasmi/src/engine/regmach/executor/mod.rs, crates/wasmi/src/engine/regmach/mod.rs, crates/wasmi/src/engine/regmach/trap.rs, crates/wasmi/src/engine/resumable.rs, crates/wasmi/tests/e2e/v1/resumable_call.rs
Closes https://github.com/paritytech/wasmi/issues/811.
=> Implement resumable calls via register-machine `wasmi` engine backend

crates/wasmi/src/engine/mod.rs, crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/module/compile/mod.rs, crates/wasmi/src/module/mod.rs, crates/wasmi/src/module/parser.rs
This is later going to be used to implement https://github.com/paritytech/wasmi/issues/817 and others.
=> Introduce `WasmTranslator` trait

crates/wasmi/src/engine/translator/tests/regression/fuzz_2.wat, crates/wasmi/src/engine/translator/tests/regression/mod.rs, crates/wasmi/src/engine/translator/visit.rs
When translating
```wat
(local.set $n (local.get $n))
```
or
```wat
(local.tee $n (local.get $n))
```
The `wasmi` translation now properly ignores this since the whole sequence can be ignored and no longer runs into preservation issues. Note: While this change fixes the tagged test case there might be more bugs in local variable preservation that we might need to fix later.
=> Fix `local.set` preservation bug

crates/wasmi/benches/benches.rs, scripts/ci/benchmarks-report.sh
~~Increase measurement time for translate tests to check whether it will help to fix report.~~
Use `mean` metric when `slope` is not produced by Criterion
=> Test criterion reports

crates/wasmi/src/engine/translator/tests/regression/mod.rs, crates/wasmi/src/module/error.rs, crates/wasmi/src/module/mod.rs, crates/wasmi/src/module/parser.rs
Closes https://github.com/paritytech/wasmi/issues/839.
=> Add `Module::validate` API from Wasmtime

.github/workflows/rust.yml
The problem is that GitHub Actions `actions-rs` got archived and is no longer expected to be maintained.
=> Make CI jobs use `dtolnay/rust-toolchain` instead of `actions-rs`

crates/wasmi/src/error.rs, crates/wasmi/tests/e2e/v1/func.rs
This adds the following APIs:
- `Error::downcast`
- `Error::downcast_ref`
- `Error::downcast_mut`
And removes the following API:
- `Error::kind_mut`
- `Error::into_kind`
=> Improve `Error` API

crates/wasmi/src/error.rs
Closes https://github.com/paritytech/wasmi/issues/855.
Unfortunately we cannot add From<HostError> for Error since that conflicts with its other From impls which is a slight bummer to user experience.
=> Add `Error::host` constructor

crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/executor/stack/mod.rs
Locally this proved to be highly effective in improving call intense work loads while not regression compute intense workloads.
=> Add inline annotations to call exec handlers

crates/wasmi/src/engine/resumable.rs
Closes https://github.com/paritytech/wasmi/issues/869.
This implicitly also grants `Sync` to the `TypedResumableInvocation` type.
@tomaka
=> Add `Sync` impl to `ResumableInvocation`

crates/wasmi/src/engine/code_map.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/executor/mod.rs, crates/wasmi/src/engine/mod.rs
Closes https://github.com/paritytech/wasmi/issues/873
=> Charge fuel for lazy compilation if enabled

crates/wasmi/src/engine/translator/tests/op/cmp/f32_ge.rs, crates/wasmi/src/engine/translator/tests/op/cmp/f32_le.rs, crates/wasmi/src/engine/translator/tests/op/cmp/f64_ge.rs, crates/wasmi/src/engine/translator/tests/op/cmp/f64_le.rs, crates/wasmi/src/engine/translator/tests/regression/fuzz_12_f32.wat, crates/wasmi/src/engine/translator/tests/regression/fuzz_12_f64.wat, crates/wasmi/src/engine/translator/tests/regression/mod.rs, crates/wasmi/src/engine/translator/visit.rs
The bug appeared when a `nan` value was referenced via a function local constant register and a `{f32,f64}.{ge,le}` used its invalid `cmp(x,x) -> true` optimization to flatten the computation to a constant `true` value.
The fix is to remove this optimization for those Wasm operator translations.
=> Fix `{f32,f64}.cmp` codegen bug

crates/wasmi/src/engine/cache.rs, crates/wasmi/src/engine/code_map.rs, crates/wasmi/src/engine/config.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/executor/instrs/memory.rs, crates/wasmi/src/engine/executor/instrs/table.rs, crates/wasmi/src/engine/executor/mod.rs, crates/wasmi/src/engine/mod.rs, crates/wasmi/src/lib.rs, crates/wasmi/src/memory/mod.rs, crates/wasmi/src/module/instantiate/mod.rs, crates/wasmi/src/store.rs, crates/wasmi/src/table/mod.rs, crates/wasmi/tests/e2e/v1/fuel_consumption.rs, crates/wasmi/tests/e2e/v1/fuel_consumption_mode.rs, crates/wasmi/tests/e2e/v1/mod.rs
Closes https://github.com/paritytech/wasmi/issues/874.
=> Improve lazy fuel consumption

crates/wasmi/src/engine/executor/instrs/return_.rs, crates/wasmi/src/engine/translator/tests/regression/fuzz_13.wat, crates/wasmi/src/engine/translator/tests/regression/mod.rs
This bug was caused by the execution of `Instruction::ReturnNezMany` (multi-value).
When the condition was `false` and the return therefore not taken, the instruction pointer was not properly updated which caused invalid behavior.
=> Fix conditional multi return bug in the Wasmi executor

crates/wasmi/src/engine/translator/tests/op/local_set.rs, crates/wasmi/src/engine/translator/visit.rs
Before this change the translator forwarded the assigned local variable instead of C. However, it is possible in this particular case to forward the constant value instead of the local variable which improves code generation of following instructions due to improved optimization opportunities.
=> Forward constants in `local.tee` translation with constant value inputs

crates/wasmi/src/engine/translator/tests/regression/fuzz_14.wat, crates/wasmi/src/engine/translator/tests/regression/mod.rs, crates/wasmi/src/engine/translator/visit.rs
This bug triggered miscompilation in cases where a `global.get g0` was surrounded by a pair of fusable instructions such as `i32.and` and `i32.eqz` and `g0` was an immutable global variable.
This caused the instructions to incorrectly fuse instead of being kept separate.
=> Fix bug with `global.get` translation of constant globals

crates/wasmi/src/engine/bytecode/mod.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/branch.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/translator/tests/op/br_table.rs, crates/wasmi/src/engine/translator/tests/regression/fuzz_15_01.wat, crates/wasmi/src/engine/translator/tests/regression/fuzz_15_02.wat, crates/wasmi/src/engine/translator/tests/regression/fuzz_15_03.wat, crates/wasmi/src/engine/translator/tests/regression/mod.rs, crates/wasmi/src/engine/translator/visit.rs
The bug caused the `index` register to be overwritten in case the translator recognized that all branching targets of the `br_table` have the same branch parameters and thus expect their branch parameters at the same set of registers. This allows the translator to produce more efficient code by inserting a `copy` instruction before an actual branch took place instead of pushing a `copy` in each branch. However, this resulted in a possibility to overwrite the `index` register.
To fix this we encoded the `copy` instruction after the `br_table` instead of before which required us to implement special handling for this in the `br_table` executor.
=> Fix codegen bug with Wasm `br_table` translation

.github/workflows/rust.yml
Closes https://github.com/paritytech/wasmi/issues/890.
=> Add CI test job using LLVM's Address Sanitizer

crates/wasmi/src/engine/translator/tests/regression/fuzz_16.wat, crates/wasmi/src/engine/translator/tests/regression/fuzz_17.wat, crates/wasmi/src/engine/translator/tests/regression/mod.rs, crates/wasmi/src/engine/translator/visit_register.rs
The problem was that an adjustment for preserved registers was forgotten. The fix thus was very simple.
=> Fix heap buffer overflow due to Wasmi codegen bug

crates/wasmi/Cargo.toml, crates/wasmi/tests/spec/run.rs
The newest wast version is 0.70 but 0.66+ introduces some new wast directives that I personally have not yet fully understood and that may not actually be useful to Wasmi's current set of implemented Wasm proposals.
=> Update `wast`: `v0.64` -> `v0.65`

crates/wasmi/tests/spec/descriptor.rs, crates/wasmi/tests/spec/mod.rs, crates/wasmi/tests/spec/run.rs
The only thing preventing `miri` from working was usage of the filesystem which we were able to eliminate by usage of the `include_str` macro.
Local compile time benchmarks signaled no significant change:
```shell
cargo clean && time cargo build --test spec_shim
```
- **Before:** `50.11s user 3.71s system 651% cpu 8.259 total`
- **After:** `49.74s user 3.64s system 652% cpu 8.179 total`
Running tests time also has not changed significantly:
```shell
cargo clean && time cargo test --test spec_shim
```
- **Before:** `11.36s user 0.10s system 339% cpu 3.378 total`
- **After:** `11.26s user 0.09s system 338% cpu 3.357 total`
=> Make Wasm spec testsuite runnable via `miri`

.github/workflows/miri.yml, .github/workflows/rust.yml
Closes https://github.com/paritytech/wasmi/issues/901.
There currently is a `wast` bug reported by `miri` so this CRON job likely won't pass until we use the fixed `wast` version once published. (https://github.com/bytecodealliance/wasm-tools/pull/1386)
=> Add Miri testing CRON job

crates/wasmi/Cargo.toml, crates/wasmi/tests/spec/run.rs
This fixes a potential UB in `miri` for our testing pipeline. Merging this PR makes our `miri` CI run for more tests.
=> Update `wast` to `v70.0.2`

.config/nextest.toml, .github/workflows/miri.yml, .github/workflows/rust.yml
This allows us to run `miri` testing with "num-cpus" threads without specifying that in the CLI.
Also this makes it possible to stop a test case after running for 2x150s (300s or 5 min).
=> Add `default-miri` `nextest` configuration

crates/wasmi/src/engine/bytecode/construct.rs, crates/wasmi/src/func/into_func.rs
This disentangles the macro heavy code and makes it a bit more readable. A superior version would be to use proc. macros and automatically generate constructors for the `Instruction` enum, however, that also introduces a lot of complexity.
=> Cleanup bytecode constructor codegen

crates/wasmi/src/engine/translator/instr_encoder.rs, crates/wasmi/src/engine/translator/visit.rs
Some non-instruction value producers such as `i32.const` interfered with instruction fusion since instruction fusion of some op-codes missed a critical check which is why we reset the `last_instr` variable. However, this was a bit dirty since it implied a state machine.
This PR implements the missing checks and removes the reset of `last_instr`.
=> Make instruction fusion more robust

crates/wasmi/src/engine/translator/tests/op/binary/i32_sub.rs, crates/wasmi/src/engine/translator/tests/op/binary/i64_sub.rs, crates/wasmi/src/engine/translator/visit.rs
This fixes a bug with a niche value when `rhs=i16::MIN` since there is no symmetric equivalent for `-i16::MIN` that fits inside an `i16` value. This made the optimization fail for `rhs=i16::MIN`. By always compiling `isub` as `iadd` with negated constant `rhs` value we avoid this situation gracefully.
=> Fix `isub` -> `iadd` simplification

crates/wasmi/src/func/caller.rs, crates/wasmi/src/store.rs
The doc mentions that `consume_fuel` would panic if it overflows the fuel counter, but we are using [checked_math under the hood ](https://github.com/wasmi-labs/wasmi/blob/e011f7d1070aa90c85fbcf0d6835a7104d1aba17/crates/wasmi/src/store.rs#L299-L305) so not sure if this is accurate.
=> Fix consume_fuel doc

crates/wasmi/Cargo.toml, crates/wasmi/src/engine/translator/instr_encoder.rs, crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/engine/translator/stack/locals.rs, crates/wasmi/src/engine/translator/stack/mod.rs, crates/wasmi/src/engine/translator/stack/provider.rs, crates/wasmi/src/engine/translator/stack/register_alloc.rs, crates/wasmi/src/engine/translator/tests/op/block.rs, crates/wasmi/src/engine/translator/tests/op/br_if.rs, crates/wasmi/src/engine/translator/tests/op/if_.rs, crates/wasmi/src/engine/translator/tests/regression/conditional_preserve.rs, crates/wasmi/src/engine/translator/tests/regression/mod.rs, crates/wasmi/src/engine/translator/visit.rs, crates/wasmi/src/engine/translator/visit_register.rs
This supposedly fixes https://github.com/wasmi-labs/wasmi/issues/934.
This is still in draft due to the following reasons and ToDos:
- I couldn't find a single test case that was invalid before these changes but valid after. My theory is that for `loop` control flow structures local preservation is not needed because it is not possible to conditionally skip local manipulation without using `block` or `if` within the `loop` body somewhere. Someone please proof me wrong.
- The current WIP implementation is very wasteful with memory allocations and the old data structures to manage the locals on the stack are not ideal for their current job. I already know how to fix both problems but the work needs to be done prior to merging to avoid creating new attack surfaces.
- This is an optimization …
=> Preserve locals before entering control flow during compilation

crates/wasmi/src/memory/buffer.rs, crates/wasmi/src/memory/error.rs, crates/wasmi/src/memory/mod.rs
Draft for static buffer as an alternative to allocating memory. Closes #878.
User can give `fn() -> Option<&'static mut [u8]>`, which is a factory for static buffers. I personally only need one, but there are problems if we want user to provide `&'static mut [u8]`. It is not `Copy` or `Clone` for obvious reasons, but `Config` is. It also cannot be wrapped in `RefCell` to be taken from config by shared reference, because there is a `Sync` assert. 
In my code, this feature could used in 100% safe way:
```rust
fn static_buffer_factory() -> Option<&'static mut [u8]> {
#[repr(align(32))]
struct Memory([u8; 64 * 1024]);
// Now the linker will refuse to create the final binary
// if there is not enough space in the target RAM
static WASMI_LINEAR_MEMORY: StaticCell<Memory> = StaticCell::new();
// …
```
=> feat: add static buffer as an alternative to allocating memory

crates/cli/src/args.rs, crates/cli/src/main.rs, crates/cli/tests/run.rs
Fix #955.
This prevents the initial "executing File ..." message unless `--verbose` is set.
The only other informational message I found was the remaining fuel message. I didn't require verbose for this, since it already depends on the fuel option. But it's something to consider in the future perhaps.
=> Add verbose mode to wasmi cli

crates/wasmi/src/lib.rs
Currently, `Read` cannot be implemented outside of the crate because the `read` method signature uses `ReadError` which is public but not exported. The PR exports it.
=> Export ReadError

crates/wasmi/Cargo.toml
I just noticed that the last Wasmi `v0.32.0-beta.8` release exploded the Wasmi package size on crates.io.
The cause is probably this PR (https://github.com/wasmi-labs/wasmi/pull/954) where I unified a lot of workspace package fields and probably forgot to exclude enough.
I checked with `cargo publish --list -p wasmi` and with this PR it seesm to be cleaned up again.
=> Fix crates.io Wasmi package size

crates/wasmi/src/engine/code_map.rs
Closes https://github.com/wasmi-labs/wasmi/issues/981.
This only concerns lazy function compilation.
Now it makes a proper distinction between validated and non-validated compilation.
This makes for 56x higher costs for unchecked lazy compilation and 72x higher costs for checked lazy compilation compared to the state before where we charged the same costs as a simple `memset` for function compilation.
=> Adjust fuel per byte for compiling a function

crates/wasmi/benches/benches.rs, crates/wasmi/src/func/mod.rs, crates/wasmi/src/lib.rs, crates/wasmi/src/linker.rs
Closes https://github.com/wasmi-labs/wasmi/issues/979.
cc @athei 
Most inefficiencies are in `StringInterner::get_or_insert` and in `memcmp` calls to compare definition names.
- By using an empty `""` name for the `module` name for all host functions we can improve performance by ~15%.
- This is likely due to a fast check for empty-string to avoid having to use `memcmp`.
- Introduction of `struct LenOrder(Arc<str>)` and `struct LenOrderStr(str)` wrapper types with new `Ord` implementation to avoid `memcmp` are very effective, improving performance by roughly 50%. Unfortunately this requires a single line of `unsafe` Rust code since Rust's `BTreeMap` does not support custom comparators.
=> Optimize `wasmi::Linker` host function setup

crates/wasmi/Cargo.toml, crates/wasmi/src/engine/code_map.rs, crates/wasmi/src/engine/mod.rs
Closes https://github.com/wasmi-labs/wasmi/issues/982.
This reduces the `size_of<UncompiledFuncEntity>()` from 88 bytes down to 56 bytes.
Technically we could shave off yet another 8 bytes but this would require more massive refactorings so this PR is a decent compromise.
Benchmarks conducted locally did not show significant performance regressions or improvements.
=> Reduce codemap memory usage

crates/wasmi/src/func/func_type.rs
Locally no significant performance regressions have been found.
The `linker` benchmark test cases with `same` function type improved by 20%. Though this could be a benchmark artifact.
Generally this should improve cache friendliness and in particular memory consumption of Wasmi.
=> Make `FuncType` avoid heap allocs if possible

crates/core/src/hint.rs, crates/wasmi/src/linker.rs
I was able to further optimize the `Linker` setup performance by optimizing its internal string internment.
The trick was to provide different strategies for string internment depending on whether it was to be expected that a string is already existing or not. We can easily hint this because usually `module` strings do already exist because many definitions are put under the same `module` namespace whereas definition `name`s within the same `module` usually are unique.
Local benchmarks assessed an improvement by roughly 5-7%.
=> Optimize `Linker`'s string internment

crates/wasmi/src/linker.rs
Instead of cloning the `LinkerBuilder` state onto the newly created `Linker` we now simply increment an `Arc` strong counter. I was afraid we were slowing down on all other fronts and thus didn't implement this up front but benchmarks show no significant regressions.
Instead what we can clearly see is yet another 20x speed-up for `Linker` creation via `LinkerBuilder`.
This 20x is on top of the already existing 6x improvement from the `LinkerBuilder` API before this PR.
Therefore the total speed-up is more like 120x.
=> Speed-up `LinkerBuilder::finish`

crates/wasmi/benches/benches.rs, crates/wasmi/src/lib.rs, crates/wasmi/src/linker.rs
This makes it impossible to use the `LinkerBuilder` type incorrectly.
=> Make `LinkerBuilder` type stateful

CHANGELOG.md, crates/cli/src/context.rs, crates/cli/src/main.rs, crates/wasmi/src/engine/config.rs, crates/wasmi/src/func/caller.rs, crates/wasmi/src/store.rs, crates/wasmi/tests/e2e/v1/fuel_consumption.rs, crates/wasmi/tests/e2e/v1/fuel_metering.rs, crates/wasmi/tests/spec/context.rs
- Remove `Store::{add_fuel, consume_fuel}`
- Remove `Caller::{add_fuel, consume_fuel}`
- Add `Store::{get_fuel, set_fuel}`
- Add `Caller::{get_fuel, set_fuel}`
- Add `StoreContext::get_fuel`
- Add `StoreContextMut::{get_fuel, set_fuel}`
=> Properly mirror Wasmtime fuel API

CHANGELOG.md, crates/wasmi/src/engine/mod.rs, crates/wasmi/src/lib.rs, crates/wasmi/src/module/builder.rs
Also properly mirror Wasmtime API for `Engine::weak` and `EngineWeak` docs.
=> Re-export `EngineWeak` from the `wasmi` crate

crates/wasmi/benches/benches.rs
The results we see is that Wasmi compilation is roughly 60 times slower than `memcpy`+`memset` for N bytes.
I tested this locally with target sizes of 1MB and 10MB and clearly saw a linear scaling.
These results reflect that our latest adjustments in https://github.com/wasmi-labs/wasmi/pull/988 are on point from a conservative standpoint.
=> Add some malicous translation benchmarks

crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/executor/mod.rs, crates/wasmi/src/engine/executor/stack/mod.rs, crates/wasmi/src/engine/executor/stack/values.rs, crates/wasmi/src/engine/mod.rs
Locally we see neat performance improvements:
The downside is that this makes more extensive use of `unsafe` Rust code in the `ValueStack` implementation. But I think that the performance improvements justify this change.
=> Optimize Wasmi bytecode executor `ValueStack`

.github/workflows/rust.yml, crates/collections/src/string_interner/detail.rs
Quick fix for `smodot` issues displayed in https://github.com/wasmi-labs/wasmi/issues/1018.
Proper fix still needed after this.
=> Make `wasmi_collections` compile under `no_std` + `no-hash-maps` feature combination

crates/collections/Cargo.toml, crates/collections/src/hash.rs
Reason: https://github.com/bytecodealliance/wasm-tools/pull/1536#issuecomment-2098562789
=> Remove usage of the `compile-time-rng` crate feature from the `ahash` dependency

crates/wasmi/src/memory/data.rs, crates/wasmi/src/module/builder.rs, crates/wasmi/src/module/data.rs, crates/wasmi/src/module/instantiate/mod.rs, crates/wasmi/src/module/mod.rs, crates/wasmi/src/module/parser.rs
Benchmarks revealed that parsing and handling of data sections were a big contributor to the overall spent time for some benchmarks, such as `ffmpeg.wasm`. This is probably due to heap memory allocator pressure since all of its many data segments each allocated a bit of heap memory for their bytes.
This PR bundles bytes of all active data segments into a single buffer reducing the overall memory consumption and pressure on the heap memory allocator.
Benchmarks show roughly 15% improvement for compiling `ffmpeg.wasm` in lazy compilation mode.
=> Optimize data section parsing and storage

crates/wasmi/src/module/parser.rs
Benchmarks showed that validation of the data section can be very costly for some Wasm binaries and furthermore the data section does strictly not belong to the Wasm module header. Therefore it makes sense to no longer validate it in header-only validation mode.
=> No longer validate Wasm module header in `Module::new_unchecked`

crates/collections/src/arena/dedup.rs
Previously the alloc method was optimized for `FuncType`s that already existed which was quite uncommon. Now it is optimized for the opposite case.
Compilation benchmarks show small improvements all in all.
=> Optimize `FuncType` allocations

.github/workflows/rust.yml
The `miri` CI job was taking too much time before. The 2 jobs should take roughly similar time and thus "half" the overall time it takes to check Wasmi via `miri`.
=> Split up `miri` CI job into `miri` and `miri-spec`

crates/wasmi/src/module/builder.rs
This should optimize `ModuleBuilder::finish` and generally the building process of Wasm modules.
Locally I can see some minor 2-5% performance wins especially for the `lazy` translation test cases where the impact is especially visible.
=> Improve memory reservations in `ModuleBuilder`

crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/executor/mod.rs, crates/wasmi/src/engine/executor/stack/values.rs, crates/wasmi/src/error.rs, crates/wasmi/src/module/instantiate/mod.rs, crates/wasmi/tests/e2e/v1/resumable_call.rs
This was an oversight in #1041.
=> Unpack `ResumableHostError` for non-resumeble calls

CHANGELOG.md, Cargo.toml
Closes https://github.com/wasmi-labs/wasmi/issues/999.
=> Prepare release for Wasmi `v0.32.0` stable

crates/wasmi/src/engine/translator/stack/mod.rs, crates/wasmi/src/engine/translator/stack/register_alloc.rs, crates/wasmi/src/engine/translator/tests/op/local_preserve.rs, crates/wasmi/src/engine/translator/visit.rs
Fixes the test case reported in https://github.com/wasmi-labs/wasmi/issues/1051#issuecomment-2146470314.
=> Fix local preservation when chaining `local.set`

crates/wasmi/src/engine/code_map.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/executor/mod.rs, crates/wasmi/src/engine/executor/stack/mod.rs, crates/wasmi/src/engine/executor/stack/values.rs
- This somewhat improves the whacky `ValueStack` API of Wasmi's executor engine. It introduces `extend_by` and refactors `alloc_call_frame` and removes plenty of APIs that are no longer needed due to these changes.
- The gist of this PR is that it (hopefully) needs a bit less `unsafe` code or that the `unsafe` code is isolated a bit better.
- Another hope with this PR is that performance stays the same or at best improves, especially for call-intense workloads. However, performance improvements have not been detected locally unfortunately.
- Adds `ValueStack::extend_by` method
- Removes `ValueStack::{reserve, extend_slice, extend_zeros, fill_at, stack_ptr_last_n}` methods
- Adds `FrameParams` type abstraction
- Refactors all code that is touched by the above items
=> Refactor engine's `ValueStack` API

crates/wasmi/src/engine/cache.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/executor/instrs/load.rs, crates/wasmi/src/engine/executor/instrs/memory.rs, crates/wasmi/src/engine/executor/instrs/return_.rs, crates/wasmi/src/engine/executor/instrs/store.rs
This has fewer indirections when using the default linear memory. Local perf measurements indicated up to 20% improvements for memory-intense workloads. Unfortunately it seems that call-intense workloads regress.
=> Optimize memory access in the Wasmi executor

crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/executor/instrs/memory.rs, crates/wasmi/src/engine/executor/instrs/return_.rs, crates/wasmi/src/engine/executor/instrs/table.rs, crates/wasmi/src/engine/executor/mod.rs, crates/wasmi/src/engine/executor/stack/mod.rs
This replaces the `ValueStack` and `CallStack` references with a single `Stack` reference in the `Executor`.
=> Use `Stack` in `Executor`

crates/wasmi/src/engine/executor/instrs/memory.rs, crates/wasmi/src/store.rs
Locally this yielded a performance improvement for our bulk-ops benchmark test case by roughly 3.5%.
The local test uses `memory.copy` and `memory.fill` with 5000 bytes per operation.
Note that performance wins for bulk-ops with smaller lengths are going to be way more significant.
=> Use `CachedMemory` in bulk-ops executors

crates/wasmi/src/engine/executor/cache.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/executor/instrs/global.rs, crates/wasmi/src/engine/executor/instrs/load.rs, crates/wasmi/src/engine/executor/instrs/memory.rs, crates/wasmi/src/engine/executor/instrs/return_.rs, crates/wasmi/src/engine/executor/instrs/store.rs, crates/wasmi/src/engine/executor/instrs/table.rs, crates/wasmi/src/engine/executor/stack/calls.rs
This new instance cache works very different from the old one and is supposedly way more efficient.
It relies on the executor updating it whenever the currently used `Instance` has been changed. While the executor is in control over that the `CachedInstance` provides an efficient way to access `Instance` related data.
=> Add new instance cache: `CachedInstance`

crates/wasmi/benches/benches.rs, crates/wasmi/src/engine/executor/instrs/memory.rs, crates/wasmi/src/memory/buffer.rs, crates/wasmi/src/memory/mod.rs
- Adds `Memory::{data_ptr, data_size}`
- Changes return type of `Memory::grow` from `Pages` to `u32`
- Changes `additional` parameter type from `Pages` to `u32`
- Remove `Memory::current_pages` method
- Add `Memory::size` method
=> Improve `Memory` API

crates/wasmi/src/engine/config.rs, crates/wasmi/src/lib.rs, crates/wasmi/src/module/builder.rs, crates/wasmi/src/module/custom_section.rs, crates/wasmi/src/module/mod.rs, crates/wasmi/src/module/parser.rs, crates/wasmi/src/module/parser/buffered.rs, crates/wasmi/src/module/parser/streaming.rs
Closes https://github.com/wasmi-labs/wasmi/issues/1084.
=> Support Wasm custom sections parsing and processing

crates/core/src/untyped.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/limits/engine.rs, crates/wasmi/src/engine/limits/stack.rs, crates/wasmi/src/engine/translator/error.rs, crates/wasmi/src/engine/translator/labels.rs, crates/wasmi/src/func/error.rs, crates/wasmi/src/global.rs, crates/wasmi/src/memory/error.rs, crates/wasmi/src/module/read.rs, crates/wasmi/src/store.rs, crates/wasmi/src/table/error.rs
I added an Error impl for all errors that implement Display. I am planning on making another pull request that implements Display and Error for the remaining errors later.
=> Implement `std::error::Error` for all error types that implement `Display`

crates/wasmi/src/engine/executor/cache.rs
Closes https://github.com/wasmi-labs/wasmi/issues/1091.
This can be reverted once Wasmi's MSRV is bumped to Rust 1.78 or higher.
=> Fix compilation error for Rust versions <1.78

.github/workflows/rust.yml, Cargo.toml
The problem with the current `cargo-cache` setup is that it still re-compiles all crates each run and only avoids re-downloading all the dependencies.
The `rust-cache` GitHub action promises to also avoid re-compiling all dependencies.
Link: https://github.com/Swatinem/rust-cache
=> Use `rust-cache` GitHub action in Wasmi's CI

crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/executor/mod.rs, crates/wasmi/src/engine/mod.rs, crates/wasmi/src/func/func_type.rs, crates/wasmi/src/func/mod.rs, crates/wasmi/src/linker.rs, crates/wasmi/tests/e2e/v1/host_call_instantiation.rs, crates/wasmi/tests/e2e/v1/mod.rs, crates/wasmi/tests/e2e/wat/host_call_instantiation.wat
So far it was not possible to instantiate a Wasm module in a host function that has been called from Wasmi's executor.
This was because of a dead lock that occurred due to a `RwLock<EngineResources>` which contained the `FuncTypeRegistry` which was (in the end) mainly used for resolving the number of parameter and result types of a called host function in the Wasmi executor.
There are two ways of solving this with the following change:
Remove `EngineResources` and instead `RwLock` both `CodeMap` and `FuncTypeRegistry` themselves.
1. Continue to use `&CodeMap` in the Wasmi executor but now also a `RwLock<FuncTypeRegistry>`. Unlock the registry very shortly to resolve the number of parameters and results whenever a host function is called which should occur kind of rarely. The downside is …
=> Allow Wasm module instantiation in host functions called from Wasmi's executor

Cargo.toml
This is no longer used since Rust sourced Wasmi benchmarks have been moved into a Git submodule.
=> Remove unused Cargo profile

crates/wasmi/src/engine/code_map.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/executor/mod.rs, crates/wasmi/src/engine/executor/stack/values.rs, crates/wasmi/src/engine/mod.rs, crates/wasmi/tests/e2e/v1/host_call_compilation.rs, crates/wasmi/tests/e2e/v1/mod.rs, crates/wasmi/tests/e2e/wat/host_call_compilation.wat
Closes https://github.com/wasmi-labs/wasmi/issues/631.
This is another relatively naive fix for #631. It heavily refactors the `CodeMap` to no longer use atomics for synchronization but a global `Mutex`. The idea behind this is that this is the lowest we can get with simple synchronization locks. If this technique does not suffice the performance needs, we need to look elsewhere.
Benchmarks comparing this PR with `main`:
Rust-sourced benchmarks do not significantly regress:
Call-intense benchmark regress as expected:
Other benchmarks are also not signficantly affected:
=> Allow to compile Wasm modules in host functions called from the Wasmi executor (take 2)

crates/wasmi/src/engine/bytecode/construct.rs, crates/wasmi/src/engine/bytecode/mod.rs, crates/wasmi/src/engine/code_map.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/executor/mod.rs, crates/wasmi/src/engine/executor/stack/calls.rs, crates/wasmi/src/engine/executor/stack/values.rs, crates/wasmi/src/engine/mod.rs, crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/engine/translator/relink_result.rs, crates/wasmi/src/engine/translator/tests/driver.rs, crates/wasmi/src/engine/translator/tests/fuzz/mod.rs, crates/wasmi/src/engine/translator/tests/op/call/internal.rs, crates/wasmi/src/engine/translator/tests/op/if_.rs, crates/wasmi/src/engine/translator/tests/op/local_preserve.rs, crates/wasmi/src/engine/translator/tests/op/local_set.rs, crates/wasmi/src/engine/translator/tests/op/return_call/internal.rs, crates/wasmi/src/engine/translator/visit.rs, crates/wasmi/src/func/mod.rs, crates/wasmi/src/module/builder.rs, crates/wasmi/src/module/mod.rs, crates/wasmi/src/module/parser.rs
This avoid confusion with `EngineFunc`s that have been initialized lazily and are not _yet_ compiled. `EngineFunc` is a better name because it simply states that the function is stored inside the Wasmi `Engine` which is always true for them independent of their current compilation state.
=> Rename `CompiledFunc` to `EngineFunc`

crates/collections/src/arena/mod.rs, crates/wasmi/src/engine/code_map.rs, crates/wasmi/src/engine/mod.rs, crates/wasmi/src/module/builder.rs, crates/wasmi/src/module/mod.rs, crates/wasmi/src/module/parser.rs
The new `CodeMap::alloc_funcs` replaces the `CodeMap::alloc_func` API.
The advantage is that fewer `CodeMap` locks are required to allocate multiple `EngineFunc` at the same time which is the only way `CodeMap::alloc_func` was used.
Also this PR introduces the new `EngineFuncSpan` and `EngineFuncSpanIter` abstractions which significantly improve space efficiency of storing newly allocated contiguous `EngineFunc` indices returned by `CodeMap::alloc_funcs`.
This allowed us to optimize the way `ModuleHeader` and `ModuleBuilder` store and manage allocated `EngineFunc`s.
Benchmarks conducted locally confirm that this is a huge performance improvement, especially for lazy Wasm module compilation:
=> Add `CodeMap::alloc_funcs` API

crates/wasmi/src/module/builder.rs, crates/wasmi/src/module/export.rs, crates/wasmi/src/module/instantiate/mod.rs, crates/wasmi/src/module/mod.rs
This mirrors the fact that Wasmtime's `Module` is also `Clone` which is reflected by the standardized Wasm C-API that views Wasm modules as reference types which are generally cheaply clone-able.
Benchmarks conducted locally didn't show any significant performance regressions. There were a few minor 2% perf regressions which could have also been noise.
=> Make `wasmi::Module` implement `Clone`

crates/wasmi/src/func/caller.rs, crates/wasmi/src/store.rs
Required for https://github.com/wasmi-labs/wasmi/pull/1009 to simplify API surface.
=> Return `Error` instead of `FuelError` from `Store::get/set_fuel` APIs

crates/core/src/untyped.rs, crates/wasmi/src/engine/bytecode/construct.rs, crates/wasmi/src/engine/bytecode/mod.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/conversion.rs, crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/engine/translator/relink_result.rs, crates/wasmi/src/engine/translator/tests/op/unary/conversion.rs, crates/wasmi/src/engine/translator/typed_value.rs, crates/wasmi/src/engine/translator/visit.rs, crates/wasmi/src/engine/translator/visit_register.rs
The Wasm `i64_extend_i32_u` and `i64_extend_i32_s` instructions are unnecessary in Wasmi bytecode.
- The `i64_extend_i32_u` instruction is essentially a no-op in an untyped bytecode.
- The `i64_extend_i32_s` instruction can be replaced by the `i64_extend32_s` instruction since Wasmi bytecode is untyped and the only difference between these two instructions is their effect on the type system.
Technically the `i32_wrap_i64 x` instruction could be replaced by `i64.and x 0xFFFF_FFFF` but due to Wasmi's current bytecode encoding this replacement representation would require substantially more encoding space and was less efficient.
=> Remove unnecessary extend instructions

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/args.rs, crates/wasi/Cargo.toml, crates/wasi/src/lib.rs, crates/wasi/src/sync/mod.rs, crates/wasi/src/sync/snapshots/preview_1.rs, crates/wasi/tests/wasi_wat.rs
Closes https://github.com/wasmi-labs/wasmi/issues/943.
This makes it possible to remove the old and outdated `wasi-cap-std-sync` dependency altogether.
Unfortunately with this update the `wasi-common` crate still pulls the huge `wasmtime` dependency into Wasmi and I am a bit confused why this happens.
Issue: https://github.com/bytecodealliance/wasmtime/issues/9009
=> `wasmi_wasi`: Update `wasi-common` and `wiggle` dependencies

crates/wasmi/src/engine/bytecode/construct.rs, crates/wasmi/src/engine/bytecode/mod.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/engine/translator/relink_result.rs, crates/wasmi/src/engine/translator/tests/op/call/indirect.rs, crates/wasmi/src/engine/translator/tests/op/return_call/indirect.rs, crates/wasmi/src/engine/translator/visit.rs, crates/wasmi/src/engine/translator/visit_register.rs
Simplify integration of the new Wasmi bytecode introduced [here](https://github.com/wasmi-labs/wasmi/pull/1152).
=> Implement re-designed `call_indirect` instructions

crates/wasmi/src/engine/bytecode/construct.rs, crates/wasmi/src/engine/bytecode/immediate.rs, crates/wasmi/src/engine/bytecode/mod.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/select.rs, crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/engine/translator/relink_result.rs, crates/wasmi/src/engine/translator/tests/op/local_set.rs, crates/wasmi/src/engine/translator/tests/op/mod.rs, crates/wasmi/src/engine/translator/tests/op/select.rs, crates/wasmi/src/engine/translator/visit_register.rs
This simplifies integration of https://github.com/wasmi-labs/wasmi/pull/1152.
=> Implement re-designed Wasmi `select` instructions

crates/wasmi/src/engine/bytecode/construct.rs, crates/wasmi/src/engine/bytecode/mod.rs, crates/wasmi/src/engine/bytecode/utils.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/branch.rs, crates/wasmi/src/engine/executor/instrs/copy.rs, crates/wasmi/src/engine/executor/instrs/return_.rs, crates/wasmi/src/engine/translator/instr_encoder.rs, crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/engine/translator/relink_result.rs, crates/wasmi/src/engine/translator/stack/mod.rs, crates/wasmi/src/engine/translator/tests/fuzz/mod.rs, crates/wasmi/src/engine/translator/tests/op/br_table.rs, crates/wasmi/src/engine/translator/visit.rs, crates/wasmi/src/engine/translator/visit_register.rs
This new `br_table` design fixes a pathological encoding scheme with the old `br_table` instruction when the branches required to copy values into different branch destination registers. The new design no longer has this pathological translation case and thus should use a lot less encoding space and be more efficient in some cases.
The downside is that this increased complexity in both, the Wasmi translator and also in the Wasmi bytecode executor to some extend. However, it could also be argued that the translation of the new `br_table` instructions is a bit simpler overall since the pathological case no longer has to be handled.
=> Implement re-designed Wasmi `br_table` instructions

crates/wasmi/src/engine/bytecode/construct.rs, crates/wasmi/src/engine/bytecode/mod.rs, crates/wasmi/src/engine/bytecode/utils.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/branch.rs, crates/wasmi/src/engine/translator/instr_encoder.rs, crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/engine/translator/relink_result.rs, crates/wasmi/src/engine/translator/tests/fuzz/mod.rs, crates/wasmi/src/engine/translator/tests/op/binary/i32_div_s.rs, crates/wasmi/src/engine/translator/tests/op/binary/i32_div_u.rs, crates/wasmi/src/engine/translator/tests/op/binary/i32_rem_s.rs, crates/wasmi/src/engine/translator/tests/op/binary/i32_rem_u.rs, crates/wasmi/src/engine/translator/tests/op/binary/i64_div_s.rs, crates/wasmi/src/engine/translator/tests/op/binary/i64_div_u.rs, crates/wasmi/src/engine/translator/tests/op/binary/i64_rem_s.rs, crates/wasmi/src/engine/translator/tests/op/binary/i64_rem_u.rs, crates/wasmi/src/engine/translator/tests/op/if_.rs, crates/wasmi/src/engine/translator/tests/op/load.rs, crates/wasmi/src/engine/translator/tests/op/store/mod.rs, crates/wasmi/src/engine/translator/tests/op/unary/mod.rs, crates/wasmi/src/engine/translator/visit.rs, crates/wasmi/src/engine/translator/visit_register.rs
Simplifies https://github.com/wasmi-labs/wasmi/pull/1152 integration later on.
=> Use named fields for some `Instruction` variants

crates/wasmi/src/engine/bytecode/construct.rs, crates/wasmi/src/engine/bytecode/mod.rs, crates/wasmi/src/engine/bytecode/utils.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/store.rs, crates/wasmi/src/engine/translator/relink_result.rs, crates/wasmi/src/engine/translator/visit_register.rs
=> Use named field for Wasmi `store` instructions

crates/wasmi/src/engine/bytecode/construct.rs, crates/wasmi/src/engine/bytecode/mod.rs, crates/wasmi/src/engine/executor/instrs/table.rs, crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/engine/translator/tests/fuzz/mod.rs, crates/wasmi/src/engine/translator/tests/op/load.rs, crates/wasmi/src/engine/translator/tests/op/store/mod.rs
This is no longer required since we moved to named fields for the `Instruction` enum.
=> Remove `Const32<u32>` usage

crates/wasmi/src/engine/bytecode/mod.rs, crates/wasmi/src/engine/executor/instr_ptr.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/executor/instrs/copy.rs, crates/wasmi/src/engine/executor/instrs/memory.rs, crates/wasmi/src/engine/executor/instrs/return_.rs, crates/wasmi/src/engine/executor/instrs/select.rs, crates/wasmi/src/engine/executor/instrs/store.rs, crates/wasmi/src/engine/executor/instrs/table.rs, crates/wasmi/src/engine/executor/mod.rs, crates/wasmi/src/engine/executor/stack/calls.rs
=> Move `InstructionPtr` into the executor sub-module

crates/wasmi/src/engine/bytecode/mod.rs, crates/wasmi/src/engine/translator/control_stack.rs, crates/wasmi/src/engine/translator/instr_encoder.rs, crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/engine/translator/provider.rs, crates/wasmi/src/engine/translator/stack/mod.rs, crates/wasmi/src/engine/translator/utils.rs, crates/wasmi/src/engine/translator/visit.rs
=> Move `provider` module into the `translator` module

crates/wasmi/src/engine/executor/instrs/branch.rs, crates/wasmi/src/engine/translator/tests/fuzz/mod.rs, crates/wasmi/src/engine/translator/tests/fuzz/wat/audit_0.wat
Fix for bug introduced in https://github.com/wasmi-labs/wasmi/pull/1158 post latest v0.36.0 release.
=> Fix `br_table_many` execution bug

crates/wasmi/src/engine/translator/instr_encoder.rs, crates/wasmi/src/engine/translator/relink_result.rs
Now based on the new `VisitRegs` trait.
Also simplifies integration of https://github.com/wasmi-labs/wasmi/pull/1152.
=> Refactor `relink_result` implementation

crates/wasmi/src/engine/bytecode/construct.rs, crates/wasmi/src/engine/bytecode/error.rs, crates/wasmi/src/engine/bytecode/mod.rs, crates/wasmi/src/engine/bytecode/span.rs, crates/wasmi/src/engine/bytecode/tests.rs, crates/wasmi/src/engine/bytecode/utils.rs, crates/wasmi/src/engine/bytecode/visit_regs.rs, crates/wasmi/src/engine/executor/instrs/branch.rs, crates/wasmi/src/engine/executor/instrs/copy.rs, crates/wasmi/src/engine/executor/instrs/return_.rs, crates/wasmi/src/engine/translator/control_frame.rs, crates/wasmi/src/engine/translator/instr_encoder.rs, crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/engine/translator/tests/fuzz/mod.rs, crates/wasmi/src/engine/translator/tests/mod.rs, crates/wasmi/src/engine/translator/tests/op/br_if.rs, crates/wasmi/src/engine/translator/tests/op/br_table.rs, crates/wasmi/src/engine/translator/tests/op/call/imported.rs, crates/wasmi/src/engine/translator/tests/op/call/indirect.rs, crates/wasmi/src/engine/translator/tests/op/call/internal.rs, crates/wasmi/src/engine/translator/tests/op/loop_.rs, crates/wasmi/src/engine/translator/tests/op/mod.rs, crates/wasmi/src/engine/translator/tests/op/return_.rs, crates/wasmi/src/engine/translator/tests/op/return_call/internal.rs, crates/wasmi/src/engine/translator/utils.rs, crates/wasmi/src/engine/translator/visit.rs, crates/wasmi/src/engine/translator/visit_register.rs, crates/wasmi/src/error.rs, crates/wasmi/src/lib.rs
This also simplifies integration of https://github.com/wasmi-labs/wasmi/pull/1152.
=> New reg span types & replace `RegSpanIter` with `BoundedRegSpan`

crates/wasmi/src/engine/bytecode/construct.rs, crates/wasmi/src/engine/bytecode/mod.rs, crates/wasmi/src/engine/bytecode/visit_regs.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/translator/visit.rs
=> Use named fields for `{Elem,Data}Drop` instructions

crates/wasmi/src/engine/executor/instrs/table.rs, crates/wasmi/src/module/element.rs, crates/wasmi/src/module/instantiate/mod.rs, crates/wasmi/src/module/mod.rs, crates/wasmi/src/store.rs, crates/wasmi/src/table/element.rs, crates/wasmi/src/table/mod.rs
This fixes an issue with instantiation of Wasm tables when using `global.get` as element items of globals from another Wasm module.
From the Wasm spec testsuite: Now passes with this PR.
```wast
;; Initializing a table with imported funcref global
(module $module4
(func (result i32)
i32.const 42
)
(global (export "f") funcref (ref.func 0))
)
(register "module4" $module4)
(module
(import "module4" "f" (global funcref))
(type $out-i32 (func (result i32)))
(table 10 funcref)
(elem (offset (i32.const 0)) funcref (global.get 0))
(func (export "call_imported_elem") (type $out-i32)
(call_indirect (type $out-i32) (i32.const 0))
)
)
(assert_return (invoke "call_imported_elem") (i32.const 42))
```
=> Fix `table.init` from imported `global.get` values

crates/ir/src/for_each_op.rs, crates/ir/src/immeditate.rs, crates/ir/src/index.rs, crates/ir/src/lib.rs, crates/ir/src/visit_regs.rs, crates/wasmi/src/engine/config.rs, crates/wasmi/src/engine/executor/cache.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/load.rs, crates/wasmi/src/engine/executor/instrs/memory.rs, crates/wasmi/src/engine/executor/instrs/store.rs, crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/engine/translator/tests/op/load.rs, crates/wasmi/src/engine/translator/tests/op/memory/memory_copy.rs, crates/wasmi/src/engine/translator/tests/op/memory/memory_fill.rs, crates/wasmi/src/engine/translator/tests/op/memory/memory_grow.rs, crates/wasmi/src/engine/translator/tests/op/memory/memory_init.rs, crates/wasmi/src/engine/translator/tests/op/memory/memory_size.rs, crates/wasmi/src/engine/translator/tests/op/store/i32_store.rs, crates/wasmi/src/engine/translator/tests/op/store/i32_store16.rs, crates/wasmi/src/engine/translator/tests/op/store/i32_store8.rs, crates/wasmi/src/engine/translator/tests/op/store/i64_store.rs, crates/wasmi/src/engine/translator/tests/op/store/i64_store16.rs, crates/wasmi/src/engine/translator/tests/op/store/i64_store32.rs, crates/wasmi/src/engine/translator/tests/op/store/i64_store8.rs, crates/wasmi/src/engine/translator/tests/op/store/mod.rs, crates/wasmi/src/engine/translator/visit.rs, crates/wasmi/src/store.rs, crates/wasmi/tests/spec/mod.rs
Closes https://github.com/wasmi-labs/wasmi/issues/776.
=> Add support for Wasm `multi-memory` proposal

crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/binary.rs, crates/wasmi/src/engine/executor/instrs/branch.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/executor/instrs/comparison.rs, crates/wasmi/src/engine/executor/instrs/conversion.rs, crates/wasmi/src/engine/executor/instrs/copy.rs, crates/wasmi/src/engine/executor/instrs/global.rs, crates/wasmi/src/engine/executor/instrs/load.rs, crates/wasmi/src/engine/executor/instrs/memory.rs, crates/wasmi/src/engine/executor/instrs/return_.rs, crates/wasmi/src/engine/executor/instrs/store.rs, crates/wasmi/src/engine/executor/instrs/table.rs, crates/wasmi/src/engine/executor/instrs/unary.rs
This brings Wasmi `main` executor performance roughly on par with `v0.36.2`.
=> Optimize Wasmi executor

crates/ir/src/for_each_op.rs, crates/ir/src/primitive.rs, crates/wasmi/src/engine/code_map.rs, crates/wasmi/src/engine/executor/instrs/load.rs, crates/wasmi/src/engine/mod.rs, crates/wasmi/src/engine/translator/stack/consts.rs, crates/wasmi/src/engine/translator/stack/mod.rs, crates/wasmi/src/engine/translator/visit.rs, crates/wasmi/src/engine/utils.rs
- correctly spell `[un]signed`.
- fix comment for `last_index` - we may also want to find a better name.
- remove unused method `adjust_for_call`.
- fix comment stating `store` instead of `load`.
- re-instate panic for `CompiledFuncEntity::new` when there are more than `i32::MAX` instructions.
- `BranchOffset` API: remove invalid comment about panics.
- `CodeMap::get_compiled`: conditionally panic if `debug_assertions` are enabled.
=> Fix minor findings

crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/engine/translator/tests/op/select.rs
This fixes a bug where `select` with a constant condition (e.g. `i32.const 0`) propagates either `lhs` or `rhs` forward without encoding a `select` instruction while not protecting an eventually propagated register from the dynamic or preservation space from overwrites.
A new translation, regression unit test was added.
=> Fix bug in `select` constant propagation

crates/wasmi/Cargo.toml, crates/wasmi/src/engine/code_map.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/branch.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/executor/instrs/copy.rs, crates/wasmi/src/engine/executor/instrs/load.rs, crates/wasmi/src/engine/executor/instrs/memory.rs, crates/wasmi/src/engine/executor/instrs/return_.rs, crates/wasmi/src/engine/executor/instrs/select.rs, crates/wasmi/src/engine/executor/instrs/store.rs, crates/wasmi/src/engine/executor/instrs/table.rs, crates/wasmi/src/engine/utils.rs
This PR
- adds a new crate feature: `extra-checks`
- improves asserts and their messages for builds with `debug-assertions` or `extra-checks` enabled.
- removes certain Wasmi executor checks that rely on Wasmi translation invariants if `debug-assertions` and `extra-checks` are disabled.
- benchmarks conducted locally show a maximum performance penalty for enabled checks of up to 20%. However, it depends on the exact workload.
New crate feature: `extra-checks`
```toml
#
#
#
extra-checks = []
```
=> Add optional `extra-checks` to Wasmi executor and make checking more consistent

crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/return_.rs
This removes the kinda useless `ReturnOutcome` without any real performance or semantics change.
=> Use Rust's `ControlFlow` type in `return` instructions execution handlers

crates/cli/Cargo.toml, crates/collections/Cargo.toml, crates/wasmi/Cargo.toml
This usually has a positive effect on performance and memory usage, especially on smaller and medium sized Wasm binaries.
=> Add `no-hash-maps` crate feature to `wasmi_cli` + enable by default

crates/wasmi/benches/benches.rs
- Improves naming (ID) of translation benchmarks.
- Add benchmarks for lazy+unchecked translation.
Improvements are also required to analyze performance implications of https://github.com/wasmi-labs/wasmi/pull/1141.
=> Improve and extend translation benchmarks

.github/workflows/rust.yml, Cargo.lock, fuzz/Cargo.toml, fuzz/fuzz_targets/differential.rs, fuzz/fuzz_targets/execute.rs, fuzz/fuzz_targets/translate.rs, fuzz/fuzz_targets/translate_metered.rs, fuzz/fuzz_targets/utils.rs
This switches over the fuzz targets from using libfuzzer to using honggfuzz, which has a couple of nice features:
Honggfuzz detects how many cores are available on the host and launches as many processes as it can to maximize execution rate, no manual intervention is necessary here.
It also has support for hardware based feedback, like instruction/branch count, and on Intel hardware it can do edge coverage. This removes the need for compiling with instrumentation which creates a large speedup. It isn't enabled in this PR, because it looks unlikely that the github runners enable access to the perf counters for this feature, but it's available should these targets ever be run on hardware that supports it.
https://honggfuzz.dev/
=> Use Honggfuzz for fuzzing targets

crates/ir/src/for_each_op.rs
=> Improve/update `Instruction` docs

crates/ir/src/primitive.rs, crates/wasmi/src/engine/translator/tests/op/cmp_br.rs, crates/wasmi/src/engine/translator/tests/op/i32_eqz.rs
- This also fixes a bug in the `ComparatorAndOffset` -> `UntypedVal` impl.
- Also it adds a missing test for `cmp+br` fallback instruction translation.
=> Add more translation tests for fused-`i32_eqz` and `cmp+br` instrs

.config/nextest.toml
This should make it less likely that the `Miri (spec)` CI job will time out.
=> Bump `nextest` timeout to 360s from 300s

.github/workflows/rust.yml, Cargo.lock, fuzz/Cargo.toml, fuzz/fuzz_targets/differential.rs, fuzz/fuzz_targets/execute.rs, fuzz/fuzz_targets/translate.rs, fuzz/fuzz_targets/translate_metered.rs
Unfortunately I have had problems using `honggfuzz` locally since its `Makefile` disallowed building for my MacOS version (most recent one). In all honesty, I have not dug deeply into this issue. This PR makes our fuzzing infrastructure use `libfuzzer-sys` again which seems to be the "Rust industry" standard as of today and thus it is expected that we will have the least issues using it.
cc @Scott-Guest @gtrepta
=> Use `libfuzzer` for fuzzing again

.github/workflows/rust.yml
- Using 4 threads instead of just 2.
- GitHub hosted runners provide 4 CPU for `ubuntu-latest`.
- Update Rust nightly toolchain version.
- Add some more comments for fuzzing run command.
- Add quick type-check step for fuzzing targets.
=> Update and improve fuzzing CI

.github/workflows/rust.yml, fuzz/Cargo.toml
We reduce compile time for `translate` and `execute` fuzzers by not making them have to compile Wasmtime and Wasmi (stack) since they don't need it. Instead those heavy dependencies are only compiled in for the `differential` fuzzer which requires them.
=> Improve fuzzer compile times

fuzz/fuzz_targets/differential.rs
The problem is that now multiple function could be run. If one function displays non-deterministic behavior between Wasmi and the other oracle, following function calls can be influenced by this via global state, for example global variable state. Thus a run needs to stop immediately after encountering non-determinism.
=> Skip fuzz run after encountering the first non-determinism

.github/workflows/rust.yml, crates/cli/Cargo.toml, crates/collections/Cargo.toml, crates/collections/src/lib.rs, crates/collections/src/map.rs, crates/collections/src/set.rs, crates/collections/src/string_interner.rs, crates/wasmi/Cargo.toml
This allows to drop some `wasmi_collections` dependencies when unused for improved compile times.
Wasmi users who previously used `no-hash-maps` should simply use `prefer-btree-collections` now instead to make sure to always use btree-based collections in their compiled artifacts.
- Removes `no-hash-maps` crate feature. Also remove it from `default` feature set.
- Adds `hash-collections` crate feature.
- Adds `prefer-btree-collections` crate feature.
Feature/collections usage matrix:
| `hash-collections` | `prefer-btree-collections` | usage |
|:---:|:---:|:---|
| false | false | btree (default) |
| true | false | hash |
| false | true | btree |
| true | true | btree |
Similar to: https://github.com/bytecodealliance/wasm-tools/pull/1866/files
Will be even more useful once …
=> Refactor crate features for more control over hash-maps usage

Cargo.lock, crates/core/Cargo.toml, crates/core/src/untyped.rs
The `paste` proc. macro dependency only has a single use in the `wasmi_core` crate which can be easily removed.
=> Remove `paste` dependency

crates/wasmi/tests/spec/mod.rs, crates/wasmi/tests/spec/runner.rs
This encapsulates data and code of directives processing from data and code required for Wasmi operations.
=> Introduce Wast directives processor for `WastRunner`

crates/wasmi/src/linker.rs
Adds the following `Linker` APIs:
- `Linker::allow_shadowing`: configures the `Linker` to allow to shadow previous definitions without errors.
- `Linker::instance`: convenience method to define all exports of an `Instance`.
- `Linker::alias_module`: convenience method to add a module aliasing name.
=> Add new `Linker` APIs

crates/wasmi/src/lib.rs
The current example provided in the documentation fails to build because it uses the `wat` without a reference. This PR adds the necessary use statement.
=> Add missing import

crates/wast/src/lib.rs
These warning fixes can be removed once `wasmi_wast` uses the next version of the `wast` crate (v220) which includes fixes for these issues: https://github.com/bytecodealliance/wasm-tools/pull/1891
=> Fix or silence `wasmi_wast` warnings

crates/wasmi/tests/spec/mod.rs, crates/wast/src/lib.rs
This updates the Wasm spec testsuite that Wasmi's tests are using to the most recent commit.
=> Update Wasm spec testsuite

crates/c_api/src/config.rs
`config.h` defines `WASMI_CONFIG_PROP` to define setters for configuration options as `wasmi_config_##name##_set`. Just like for all other configuration options, this macro is used for `compilation_mode`.  However, the function is exported from the `c_api` crate with a different name.
Fix the exported name and make it consistent with the other configuration options.
=> C API: Fix function name of compilation mode setter

crates/core/src/untyped.rs, crates/core/src/value.rs, crates/ir/src/for_each_op.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/load.rs, crates/wasmi/src/engine/executor/instrs/store.rs, crates/wasmi/src/engine/translator/instr_encoder.rs, crates/wasmi/src/engine/translator/tests/fuzz/mod.rs, crates/wasmi/src/engine/translator/tests/op/load.rs, crates/wasmi/src/engine/translator/tests/op/store/f32_store.rs, crates/wasmi/src/engine/translator/tests/op/store/f64_store.rs, crates/wasmi/src/engine/translator/tests/op/store/i32_store.rs, crates/wasmi/src/engine/translator/tests/op/store/i64_store.rs, crates/wasmi/src/engine/translator/visit.rs
Closes https://github.com/wasmi-labs/wasmi/issues/1302.
=> Lower `load` and `store` instructions by pruning types where possible

crates/collections/Cargo.toml
This no longer enables `string-interner` usage when enabling `std` crate feature without also enabling `hash-collections`.
=> Conditionally foward the `std` crate feature for `string-interner`

Cargo.lock, crates/collections/Cargo.toml, crates/collections/src/hash.rs
This also removes the `ahash` dependency and instead uses `hashbrown`'s default hashing utilities which is implemented by `foldhash` since v0.15.0.
=> Update `string-interner` and `hashbrown` dependencies

crates/fuzz/src/oracle/wasmtime.rs
The config in the wasmtime oracle for differential fuzzing wasn't being used, this fixes that.
It also disables POSIX signals in the config because some fuzzers (ie. honggfuzz) will catch them and report false positives. A couple examples of these signals are SIGILL for bad instructions, and SIGSEGV when there's an out of bounds load in the webassembly. [More info.](https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.signals_based_traps)
=> Use the config in the wasmtime oracle

crates/c_api/Cargo.toml, crates/c_api/src/config.rs, crates/c_api/src/engine.rs, crates/c_api/src/extern.rs, crates/c_api/src/foreign.rs, crates/c_api/src/frame.rs, crates/c_api/src/func.rs, crates/c_api/src/global.rs, crates/c_api/src/instance.rs, crates/c_api/src/lib.rs, crates/c_api/src/memory.rs, crates/c_api/src/module.rs, crates/c_api/src/ref.rs, crates/c_api/src/store.rs, crates/c_api/src/table.rs, crates/c_api/src/trap.rs, crates/c_api/src/types/export.rs, crates/c_api/src/types/extern.rs, crates/c_api/src/types/func.rs, crates/c_api/src/types/global.rs, crates/c_api/src/types/import.rs, crates/c_api/src/types/memory.rs, crates/c_api/src/types/table.rs, crates/c_api/src/types/val.rs, crates/c_api/src/val.rs, crates/c_api/src/vec.rs
=> fix: Revert `mangle-symbols` feature

crates/c_api/Cargo.toml, crates/c_api/macro/lib.rs, crates/c_api/src/config.rs, crates/c_api/src/engine.rs, crates/c_api/src/extern.rs, crates/c_api/src/foreign.rs, crates/c_api/src/frame.rs, crates/c_api/src/func.rs, crates/c_api/src/global.rs, crates/c_api/src/instance.rs, crates/c_api/src/lib.rs, crates/c_api/src/memory.rs, crates/c_api/src/module.rs, crates/c_api/src/ref.rs, crates/c_api/src/store.rs, crates/c_api/src/table.rs, crates/c_api/src/trap.rs, crates/c_api/src/types/export.rs, crates/c_api/src/types/extern.rs, crates/c_api/src/types/func.rs, crates/c_api/src/types/global.rs, crates/c_api/src/types/import.rs, crates/c_api/src/types/memory.rs, crates/c_api/src/types/table.rs, crates/c_api/src/types/val.rs, crates/c_api/src/val.rs, crates/c_api/src/vec.rs
Hello again! 
This small patch adds a `prefix-symbols` feature that adds a `wasmi_` prefix to all the public symbols that did not have it before, keeping the symbols not mangled. This way, users (that need to use `wasmi`'s c_api implementation with other backends) need not worry about `Option<Box<_>>`es but can simply use `bindgen` to take care of it. 
I think that this method makes more sense than the other one we ended up merging.
Again, thank you in advance for taking the time to review the PR.
=> Add `prefix-symbols` feature

crates/c_api/macro/lib.rs, crates/c_api/src/store.rs
Follow-up for https://github.com/wasmi-labs/wasmi/pull/1315.
cc @xdoardo
- Improves error handling and error reporting.
- Makes macro code more readable.
- Adds new checks to guard against misuse.
- Remove misuses for non-Wasm spec API functions.
=> Improve C-API `prefix_symbol` attribute macro

crates/wasmi/src/engine/executor/instrs/memory.rs, crates/wasmi/src/engine/resumable.rs, crates/wasmi/src/engine/translator/driver.rs, crates/wasmi/src/func/mod.rs
Detected during an extension of the `useless_conversion` Clippy lint.
=> chore: remove unnecessary type conversions

crates/wasmi/Cargo.toml, crates/wasmi/src/error.rs, crates/wasmi/src/module/mod.rs
A test-only `wat2wasm` function has been implemented several times in the Wasmi codebase, especially in tests which is an indicator that this functionality was crucially missing from Wasmi's module parsing.
Thus we added this feature optionally behind the new `wat` crate feature in Wasmi.
This also improves Wasmi's Wasmtime API mirroring because Wasmtime also provides `.wat` parsing support in its `Module::new` API.
We explicitly do _not_ support `.wat` parsing in `Module::new_streaming` since there is no streaming parsing support for `.wat` files via the used `wat` crate.
=> Add optional `.wat` module support to `Module::new`

crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/executor/instrs/return_.rs, crates/wasmi/src/engine/tests/host_calls.rs
Tail calling host functions did not properly manipulate the value- and call stack which resulted in crashes.
Fortunately tail calls that invoke host functions are rather rare which is probably the reason why this has been undetected.
Our fuzzing infrastructure could use some improvement by making it possible to fuzz host function calls which currently is not possible. A simple solution could be to allow function imports and generate host functions on the fly depending on the imported functions when setting up a Wasm instance. The difficulty is that each Wasm oracle needs to allow for this.
Another downside is that the code surrounding function calls in the Wasmi executor is probably the messiest part of the entire Wasmi codebase. We really should investigate some resources to clean-up …
=> Fix execution of tail calling host functions from Wasm

crates/wasmi/src/engine/translator/tests/fuzz/mod.rs, crates/wasmi/src/lib.rs, crates/wasmi/src/tests.rs
So far Wasmi only has a proper testing abstraction for translation tests, namely `TranslationTest`. With this PR we also add a proper abstraction for execution tests that do not necessitate a whole `.wast` file.
=> Add `ExecutionTest` utility

Cargo.lock, crates/fuzz/Cargo.toml, crates/fuzz/src/oracle/wasmtime.rs
This is a fix to OSS-Fuzz time-out caused by slow translation performance of Wasmtime which has been discussed [here](https://github.com/bytecodealliance/wasmtime/issues/10033).
In the linked GitHub issue discussion some solutions have been presented:
1) Disable Cranelift optimizations and use single-pass register allocation.
2) Use Winch backend instead of the Cranelift backend.
In this PR I decided to go with 1) since it is less disruptive, fixes the time-out issue very well and the Cranelift backend is also way more mature.
In the long term we might want to switch over to the Winch backend, since it is the more ideal backend for differential fuzzing.
=> fuzzing: speed-up Wasmtime translation performance

Cargo.lock, fuzz/Cargo.toml, fuzz/fuzz_targets/differential.rs
Using the new `FuzzInput` struct we now have properly supported `Debug` output on detected fuzzing failure test cases.
- This debug output shows the chosen Wasm runtime oracle, the `wasm_smith` module configuration and the Wasm source as `.wat` source code.
- In contrast to the already implemented `crash-inputs` feature this information is properly displayed on CI consoles.
```console
Failing input:
fuzz/artifacts/differential/crash-ec8b55496c8cf9fd654f076239bf3f25d37e6a43
Output of `std::fmt::Debug`:
FuzzInput {
chosen_oracle: Wasmtime,
module: Module {
config: Config {
available_imports: None,
exports: None,
allow_start_export: true,
allowed_instructions: InstructionKinds(
FlagSet(NumericInt | Numeric | VectorInt | Vector | Reference | Parametric | Variable | Table | MemoryInt | Memory …
```
=> Improve debug output of differential fuzzing

fuzz/fuzz_targets/differential.rs
This does not widen the amount of code that the differential fuzzer is able to cover but it speeds-up coverage guided fuzzing by providing the fuzzer with more knobs to extend covered code.
=> Allow parameter randomization for differential fuzzer

Cargo.lock, crates/collections/Cargo.toml
Closes https://github.com/wasmi-labs/wasmi/issues/1366.
[`string-interner` v0.19 release notes](https://github.com/Robbepop/string-interner/releases/tag/v0.19.0)
cc @jonhoo
=> Update `string-interner` to v0.19

crates/core/src/untyped.rs, crates/ir/src/lib.rs, crates/ir/src/primitive.rs, crates/wasmi/src/engine/executor/instrs/load.rs, crates/wasmi/src/engine/executor/instrs/store.rs, crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/engine/translator/tests/fuzz/mod.rs
This PR optimizes the Wasmi executor when executing load and store instructions with a constant `ptr` value.
Also this PR checks at translation time if a constant `ptr+offset` address is out of bounds for both the `memory.max()` and a system `usize` value and generates an appropriate trap in those cases instead of a load or store instruction.
Benchmarks didn't show a significant improvement, though this PR includes enough readability and type safety improvements that I still would want to merge it.
=> Optimize memory accesses with constant `ptr` value

crates/ir/src/for_each_op.rs, crates/wasmi/src/engine/executor/instrs/memory.rs, crates/wasmi/src/engine/translator/tests/op/memory/memory_grow.rs, crates/wasmi/src/engine/translator/visit.rs
This fixes a panic in the Wasmi translator when translating a `memory.grow` operation with a `i64` delta parameter under the `memory64` Wasm proposal.
This fix probably needs backporting for Wasmi 0.41.
=> Fix `memory64` `memory.grow` with an immediate `delta` parameter

crates/cli/Cargo.toml
During debugging I found out that the Wasmi CLI can no longer read Wat files. The reason is that we forgot to enable the `wat` crate feature for Wasmi during some refactorings. Trivial fix.
This fix needs to be backported to Wasmi v0.41.
=> Fix Wasmi CLI `.wat` files support

crates/core/src/untyped.rs
This will simplify design and implementation of https://github.com/wasmi-labs/wasmi/issues/1389.
=> Use macro to generate most of the `UntypedVal` API

crates/fuzz/src/module.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/mod.rs, crates/wasmi/src/engine/translator/utils.rs
=> chore: fix some typos in comments

crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/engine/translator/tests/driver.rs, crates/wasmi/src/engine/translator/tests/op/mod.rs, crates/wasmi/src/engine/translator/tests/op/wide_arithmetic.rs
Fixed https://github.com/bytecodealliance/wasmtime/issues/10418.
The const-evaluator pushed the `lo` and `hi` values in reversed order back into the translation stack during const-eval. I checked the other `wide-arithmetic` instructions but there it was all working as expected.
This PR adds a regression test.
=> Fix const evaluation in `mul_wide` instructions

crates/wasmi/src/engine/executor/instrs/call.rs
This fixes (or silences) a `clippy` warning.
=> Explicitly drop `ControlFlow` when not needed in the Wasmi executor

crates/core/src/lib.rs, crates/core/src/memory.rs, crates/core/src/value.rs, crates/core/src/wasm.rs
This is going to be useful for https://github.com/wasmi-labs/wasmi/pull/1395.
=> Move `wasmi_core` memory utilities into its own `memory` submodule

crates/core/src/memory.rs, crates/core/src/wasm.rs
This now exposes `load`, `load_at`, `store` and `store_at` functions additionally to the `load_extend` and `store_wrap` ones from the `wasmi_core::memory` submodule. 
This way we no longer require the weird `WrapInto` and `ExtendInto` impls for `T -> T` which made no sense.
Furthermore, this is going to simplify implementation of https://github.com/wasmi-labs/wasmi/pull/1395.
=> Refactor `wasmi_core::memory` submodule

.github/workflows/miri.yml
This broke with https://github.com/wasmi-labs/wasmi/pull/1403.
=> Fix `miri` cron CI job

crates/ir/Cargo.toml, crates/ir/src/enum.rs, crates/ir/src/for_each_op.rs, crates/ir/src/lib.rs, crates/ir/src/primitive.rs, crates/ir/src/visit_regs.rs, crates/wasmi/Cargo.toml, crates/wasmi/src/engine/executor/instrs.rs
Implements `wasmi_ir` part of https://github.com/wasmi-labs/wasmi/issues/1364.
- Adds the `simd` crate feature to `wasmi_ir`.
- Adds `Instruction` variants for all Wasm `simd` instructions when `simd` crate feature is enabled.
Link to Wasm 3.0 Spec: https://webassembly.github.io/spec/core/appendix/index-instructions.html
🟡 Means that the Wasm instruction has no Wasmi instruction counterpart by design.
| Status | Wasm `simd` Instruction |
|:-:|:-|
| 🟡 | `v128.const(imm: ImmByte[16]) -> v128` |
| ✅ | `i8x16.splat(x: i32) -> v128` |
| ✅ | `i16x8.splat(x: i32) -> v128` |
| ✅ | `i32x4.splat(x: i32) -> v128` |
| ✅ | `i64x2.splat(x: i64) -> v128` |
| ✅ | `f32x4.splat(x: f32) -> v128` |
| ✅ | `f64x2.splat(x: f64) -> v128` |
|  |  |
| ✅ | `i8x16.extract_lane_s(a: v128, imm: ImmLaneIdx16) -> i32` | …
=> `wasmi_ir`: add support for the Wasm `simd` proposal

.github/workflows/rust.yml, crates/core/src/simd.rs
This also adds a CI job to catch bugs like these in the future.
=> Fix `wasmi_core`'s `no_std` build when `simd` is enabled

crates/wasmi/Cargo.toml, crates/wasmi/src/engine/config.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/engine/translator/simd/mod.rs, crates/wasmi/src/engine/translator/simd/visit.rs, crates/wasmi/src/engine/translator/visit.rs
This add foundations for Wasm `simd` proposal support in the `wasmi` crate.
=> Add `wasmi` Wasm `simd` proposal support skeleton

.gitmodules
This bug happened in https://github.com/wasmi-labs/wasmi/pull/1403.
Fortunately `cargo publish --dry-run` made me aware of this.
=> Remove duplicated `git` submodules

crates/wast/src/lib.rs
This allows consuming Wasm `simd` proposal Wast tests.
=> Add support for `V128` to `wasmi_wast` crate

crates/core/src/simd.rs, crates/ir/src/enum.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/simd.rs, crates/wasmi/src/engine/executor/instrs/store.rs, crates/wasmi/src/engine/executor/instrs/utils.rs, crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/engine/translator/simd/mod.rs, crates/wasmi/src/engine/translator/simd/visit.rs, crates/wast/tests/mod.rs
| | Instruction |
|:-:|:--|
| ✅ | `v128.store8_lane(m: memarg, data: v128, imm: ImmLaneIdx16)` |
| ✅ | `v128.store16_lane(m: memarg, data: v128, imm: ImmLaneIdx8)` |
| ✅ | `v128.store32_lane(m: memarg, data: v128, imm: ImmLaneIdx4)` |
| ✅ | `v128.store64_lane(m: memarg, data: v128, imm: ImmLaneIdx2)` |
=> Implement `v128.storeN_lane` SIMD instruction translation and execution

crates/wasmi/src/engine/translator/simd/mod.rs, crates/wasmi/src/engine/translator/simd/visit.rs
- Fixed a bug in `i8x16.shuffle` translation where it missed a trivial check for reachability.
- Fixed an encoding bug for `v128.storeN_lane` instructions with offsets that could not be 8-bit encoded.
- Fixed a bug in `v128.shift` instruction translation with immediate `rhs` shift amounts.
=> Fix some SIMD bugs found by fuzzing

crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/simd.rs, crates/wasmi/src/engine/executor/instrs/utils.rs, crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/func/into_func.rs
Closes https://github.com/wasmi-labs/wasmi/issues/1435.
- This allows using `V128` values in the `TypedFunc` API.
- This PR also fixes some minor warnings when compiling `wasmi` without the `simd` feature enabled.
=> implement `WasmTy` for `V128`

crates/wasmi/src/engine/executor/instrs/simd.rs
The bug was that for `i8x16.replace_lane` with an immediate `i8` value the instruction pointer was bumped by 2 instead of 1.
Test case:
```wasm
(module
(global (;0;) (mut i64) i64.const 0)
(global (;1;) (mut v128) v128.const i32x4 0x00000000 0x00000000 0x00000000 0x00000000)
(global (;2;) (mut i32) i32.const 1000)
(func (export "0") (result v128)
(local v128)
i32.const 1633902446
i32x4.splat
f32x4.ceil
local.tee 0
v128.const i32x4 0x7fc00000 0x7fc00000 0x7fc00000 0x7fc00000
local.get 0
local.get 0
f32x4.eq
v128.bitselect
i32.const 1633902446
i8x16.replace_lane 14
loop (result v128) ;; label = @1
global.get 2
i32.eqz
if ;; label = @2
unreachable
end
global.get 2
i32.const 0
i32.sub
global.set 2
i32.const 1869182049
f64.const 0x1.100d0d0d02e34p+470 …
```
=> Fix bug in `v128.replace_lane` execution

crates/core/src/simd.rs
These methods are unused in Wasmi since Wasmi translates those `relaxed-simd` operators as their non-relaxed counterparts. However, for completeness I think it makes sense to add these missing `relaxed-simd` methods to `wasmi_core` since it tries to be a general purpose Wasm SIMD API.
=> `wasmi_core`: Add missing forwarding functions from the Wasm `relaxed-simd` proposal

.github/workflows/rust.yml
- All CI jobs that use Rust `nightly` now use the same pinned nightly Rust version. This helps with CI caching.
- The `udeps` job no longer uses caching as it is not really worth it.
- The used nightly Rust version has been update to `nightly-2025-03-30`.
=> Improve GitHub Actions CI

crates/core/src/untyped.rs, crates/ir/src/error.rs, crates/wasmi/src/engine/executor/instrs/call.rs, crates/wasmi/src/engine/limits/engine.rs, crates/wasmi/src/engine/limits/stack.rs, crates/wasmi/src/engine/translator/error.rs, crates/wasmi/src/engine/translator/labels.rs, crates/wasmi/src/error.rs, crates/wasmi/src/func/error.rs, crates/wasmi/src/global.rs, crates/wasmi/src/linker.rs, crates/wasmi/src/memory/error.rs, crates/wasmi/src/module/instantiate/error.rs, crates/wasmi/src/module/read.rs, crates/wasmi/src/store.rs, crates/wasmi/src/table/error.rs, crates/wasmi/tests/integration/host_call_instantiation.rs
This way we no longer have to conditionally compile for `std`.
=> Implement `core::error::Error` for all error types

crates/wasmi/tests/integration/resource_limiter.rs
They now also consume less memory during test execution.
=> Clean up `ResourceLimiter` integration tests

crates/wasmi/src/module/utils.rs
Carved out from #1460.
This is in anticipation to simplify merging the original PR.
=> Make `FromWasmparser` impls only use pub APIs

crates/wasmi/src/engine/executor/instrs/global.rs, crates/wasmi/src/global.rs
Carved out from #1460.
This is in anticipation to simplify merging of the original PR.
=> Re-design `GlobalEntity` API

crates/wasmi/src/module/instantiate/mod.rs, crates/wasmi/src/store.rs
This was an oversight in https://github.com/wasmi-labs/wasmi/pull/1474.
=> Remove unused `StoreInner` API

crates/wasmi/src/linker.rs, crates/wasmi/src/memory/mod.rs, crates/wasmi/src/table/mod.rs
These checks are also performed in the underlying `module.instantiate` call.
=> Avoid duplicate checks in `Linker` instantiation

crates/wasmi/src/engine/translator/mod.rs
A bug in rust-analyzer but I want to get rid of the annoying warnings.
=> Unconfuse `rust-analyzer`

crates/ir/src/for_each_op.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/memory.rs, crates/wasmi/src/engine/executor/instrs/table.rs, crates/wasmi/src/engine/translator/tests/op/memory/memory_copy.rs, crates/wasmi/src/engine/translator/tests/op/memory/memory_fill.rs, crates/wasmi/src/engine/translator/tests/op/memory/memory_grow.rs, crates/wasmi/src/engine/translator/tests/op/memory/memory_init.rs, crates/wasmi/src/engine/translator/tests/op/table/table_copy.rs, crates/wasmi/src/engine/translator/tests/op/table/table_fill.rs, crates/wasmi/src/engine/translator/tests/op/table/table_init.rs, crates/wasmi/src/engine/translator/visit.rs
Closes https://github.com/wasmi-labs/wasmi/issues/1488.
Reduces total non-SIMD instruction count from 459 to 429. (-30)
- **Verdict:** performance is not significantly affected by these changes.
=> Redesign `bulk-memory` instruction variants

crates/ir/src/for_each_op.rs, crates/ir/src/primitive.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/branch.rs, crates/wasmi/src/engine/executor/instrs/comparison.rs, crates/wasmi/src/engine/translator/comparator.rs, crates/wasmi/src/engine/translator/instr_encoder.rs, crates/wasmi/src/engine/translator/tests/op/cmp_br.rs, crates/wasmi/src/engine/translator/tests/op/i32_eqz.rs, crates/wasmi/src/engine/translator/tests/op/i32_nez.rs
Closes https://github.com/wasmi-labs/wasmi/issues/1495.
- Performance is not affected by our benchmarks. However, out benchmarks do not really cover float heavy computation very well. So we might be missing some proper data to verify.
- In manual tests I saw lots of instances in compiled Wasm where these optimization could be applied.
=> Add negated `[branch_]f{32,64}.not_{lt,le}` instructions

crates/wasmi/src/module/parser.rs
This was an oversight that caused bugs when upgrading to `wasmparser` v0.229.0.
=> Set `WasmFeatures` for `wasmparser::Parser` in `ModuleParser`

Cargo.lock, crates/core/Cargo.toml, crates/core/src/host_error.rs
Closes https://github.com/wasmi-labs/wasmi/issues/1513.
Blocked by https://github.com/wasmi-labs/wasmi/pull/1518.
=> Remove the `downcast-rs` dependency from `wasmi_core`

crates/cli/src/args.rs, crates/wasmi/src/engine/config.rs, crates/wasmi/tests/integration/fuel_consumption.rs, crates/wasmi/tests/integration/fuel_metering.rs, crates/wast/tests/mod.rs
The [`CompilationMode::LazyTranslation`](https://docs.rs/wasmi/latest/wasmi/enum.CompilationMode.html#variant.LazyTranslation) is a better default than `CompilationMode::Eager` since it is more efficient while still upholding the important invariant that Wasm is eagerly validated.
The problem with `CompilationMode::Eager` as the default is that the discoverability of the `CompilationMode` feature is not great which leads to many people trying out Wasmi to prematurely conclude that it is slow.
=> Change `CompilationMode` default to `LazyTranslation`

crates/wasmi/src/engine/translator/func/simd/visit.rs
=> Use relative path to `FuncTranslator` internals

crates/wasmi/src/engine/translator/func/control_frame.rs, crates/wasmi/src/engine/translator/func/instr_encoder.rs, crates/wasmi/src/engine/translator/func/mod.rs, crates/wasmi/src/engine/translator/func/visit.rs, crates/wasmi/src/engine/translator/utils.rs
This also reduces the `mem::size_of::<ControlFrame>` from 48 bytes to 40 bytes.
=> Clean up and refactor `FuncTranslator`'s `ControlFrame` types

crates/wasmi/src/engine/translator/comparator.rs, crates/wasmi/src/engine/translator/func/instr_encoder.rs
This allows to share more code between `main` and #1512.
=> Add `CompareResult` extension trait for `Instruction`

crates/wasmi/src/engine/translator/func/instr_encoder.rs, crates/wasmi/src/engine/translator/func/mod.rs, crates/wasmi/src/engine/translator/func/visit.rs
This also fixes a bug that `f{32,64}.copysign` with immediate `rhs` operands did not bump the fuel counter.
=> Refactor `InstrEncoder::push_instr` API + fix fuel bug

crates/wasmi/src/module/mod.rs, crates/wast/src/lib.rs, fuzz/fuzz_targets/translate.rs
The `Module::new_streaming[_unchecked]` APIs existed in Wasmi since the very beginning (thought differently named).
They implement the streaming Wasm module creation interface which is supposedly more efficient than the non-streaming API if Wasm bytes transmission and Wasm module translation are both slow. The idea is to stream in bytes in order to build up a Wasm module incrementally. However, the streaming nature adds overhead to parsing which kinda nullifies the gains. Also Wasmi translation is extremely fast, so streaming usually adds more overhead than is reduced.
As I am not 100% certain that nobody would ever have a serious use for this API, I will deprecate it first and let users know that they shall notify me here in case they have a valid use case for this API.
Removing the …
=> Deprecate `Module::new_streaming[_unchecked]` APIs

crates/wasmi/src/engine/translator/func/control_frame.rs, crates/wasmi/src/engine/translator/func/instr_encoder.rs, crates/wasmi/src/engine/translator/func/mod.rs, crates/wasmi/src/engine/translator/labels.rs, crates/wasmi/src/engine/translator/mod.rs, crates/wasmi/src/engine/translator/utils.rs
Simplifies https://github.com/wasmi-labs/wasmi/pull/1512 by making more code sharable.
=> Refactor `Instr` and move definition to `translator::utils` submodule

crates/wasmi/src/engine/translator/func/mod.rs, crates/wasmi/src/engine/translator/func/visit.rs
Closes #1544 .
cc @saulecabrera
Minified example that caused the bug:
```wat
(module
(func (export "run") (param i64) (result i64 i64)
(i64.mul_wide_s
(i64.add
(local.get 0)
(i64.const -3)
)
(i64.const 1)
)
)
)
```
Summary: The Wasmi translator incorrectly applied an optimization for `i64.mul_wide_s` when one of its operands was `i64.const 1` and the other operand was not known to never be negative. In cases where the other operand was negative the result after the optimization was incorrect.
=> Fix incorrect optimization in `i64.mul_wide_s` translation

crates/wast/tests/local/wide-arithmetic.wast, crates/wast/tests/mod.rs
Follow-up to https://github.com/wasmi-labs/wasmi/pull/1545 to add `.wast` based regression tests.
cc @saulecabrera
=> Add local `.wast` regression tests for Wasmi's `wide-arithmetic` proposal support

crates/core/src/memory/mod.rs
Caught at https://github.com/wasmi-labs/wasmi/pull/1553 via Wasmi's execution fuzzer:
https://github.com/wasmi-labs/wasmi/actions/runs/15998303367/job/45126754018?pr=1553
Test case: `cargo run -p wasmi_cli <input>`
```wasm
(module
(memory (;0;) i64 756615 (pagesize 0x1))
(export "" (memory 0))
(data (;0;) (i64.const -1) "{")
)
```
=> Fix panic when read/write out of bounds

crates/core/src/untyped.rs, crates/wasmi/src/engine/translator/func/instr_encoder.rs, crates/wasmi/src/engine/translator/func/mod.rs, crates/wasmi/src/engine/translator/func/visit.rs, crates/wasmi/src/engine/translator/utils.rs
Pulled out from https://github.com/wasmi-labs/wasmi/pull/1512.
=> Refactor `WasmInteger` trait

crates/wast/tests/local/if.wast, crates/wast/tests/local/local-tee.wast, crates/wast/tests/mod.rs
Carved out from https://github.com/wasmi-labs/wasmi/pull/1512.
=> Add more Wasmi specific `.wast` tests

Cargo.lock, Cargo.toml, crates/fuzz/src/oracle/wasmtime.rs
Unfortunately we have to disable Wasmtime's `SinglePass` register allocator due to:
https://github.com/bytecodealliance/wasmtime/pull/10554
This was used as a fix to counteract differential fuzzing timeouts.
=> Update Wasmtime dependencies to v34

crates/wasi/src/sync/snapshots/preview_1.rs
Hey team! Found and fixed dead link in crates/wasi/src/sync/snapshots/preview_1.rs
https://github.com/WebAssembly/WASI/blob/main/phases/snapshot/docs.md - dead
https://github.com/WebAssembly/WASI/blob/snapshot-01/phases/snapshot/docs.md - new link
=> fix dead WASI `snapshot-01` docs link

crates/wasmi/benches/benches.rs, crates/wasmi/benches/wat/preserve-all-locals.wat
I added this benchmark in order to have a better comparison between `main` and #1512.
=> Add local preservation translation benchmark

.editorconfig
We already have `.rustfmt.toml` to specify how to format source code.
=> Remove ancient and redundant `.editorconfig` file

crates/wasmi/src/engine/translator/comparator.rs, crates/wasmi/src/engine/translator/tests/op/select.rs
Removed invalid `.wast` tests instead of replacing them with valid ones since we now have proper `.wast` tests fully replacing them as of https://github.com/wasmi-labs/wasmi-tests/pull/5.
=> Fix negated `select+f{32,64}.cmp` op-code fusion

Cargo.lock, crates/wasmi/Cargo.toml
Partially closes https://github.com/wasmi-labs/wasmi/issues/1609.
=> Remove dependencies used only by the old `FuncTranslator`

crates/ir/src/enum.rs, crates/ir/src/for_each_op.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/branch.rs, crates/wasmi/src/engine/executor/instrs/copy.rs, crates/wasmi/src/engine/translator/func/instrs.rs, crates/wasmi/src/engine/translator/func/mod.rs
Closes https://github.com/wasmi-labs/wasmi/issues/1607.
=> Remove `Instruction::Copy{Span,Many}` variants

Cargo.lock, crates/wasmi/Cargo.toml, crates/wasmi/src/module/init_expr.rs
This allows us to finally drop the `smallvec` dependency altogether, closing https://github.com/wasmi-labs/wasmi/issues/1622 and https://github.com/wasmi-labs/wasmi/issues/1609.
Closes #1622.
Closes #1609.
=> Remove `smallvec` usage from `ConstExpr::new` method

crates/ir/src/enum.rs, crates/ir/src/visit_regs.rs
- Removed `PartialEq` and `Eq` derives from `Instruction` enum.
- Made `Copy` and `Clone` impls on `Instruction` non derives.
- Moved `Instruction::result` definition into `define_enum` macro.
- Moved `HostVisitor` trait impl for `Instruction` into `define_enum` macro.
All above changes combined improve `wasmi_ir` compile times (`--dev`) from 2.2s -> 1.3s improving `wasmi` compile times from 5.8s -> 4.8s.
=> Improve `wasmi_ir` compile times

crates/ir/src/for_each_op.rs, crates/wasmi/src/engine/executor/instrs.rs, crates/wasmi/src/engine/executor/instrs/memory.rs, crates/wasmi/src/engine/executor/instrs/table.rs, crates/wasmi/src/engine/translator/func/mod.rs, crates/wasmi/src/engine/translator/func/visit.rs, crates/wasmi/tests/integration/fuel_consumption.rs
Closes https://github.com/wasmi-labs/wasmi/issues/1641.
Removes 9 `Instruction`s in total, all of which are costly to execute and thus usually not part of the hot-path of a Wasm program.
=> Remove `bulk-ops` immediate `Instruction` variants
